/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.23.2
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChartResponse,
  CreateChartRequest,
  HTTPValidationError,
} from '../models/index';
import {
    ChartResponseFromJSON,
    ChartResponseToJSON,
    CreateChartRequestFromJSON,
    CreateChartRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateChartsEndpointRequest {
    createChartRequest: CreateChartRequest;
}

/**
 * 
 */
export class ChartsApi extends runtime.BaseAPI {

    /**
     * Create charts.
     * Create a chart
     */
    async createChartsEndpointRaw(requestParameters: CreateChartsEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChartResponse>  | runtime.StreamApiResponse> {
        if (requestParameters['createChartRequest'] == null) {
            throw new runtime.RequiredError(
                'createChartRequest',
                'Required parameter "createChartRequest" was null or undefined when calling createChartsEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/chat/charts`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateChartRequestToJSON(requestParameters['createChartRequest']),
        }, initOverrides);

        if ('createChartRequest' in requestParameters && requestParameters['createChartRequest'] != null && 'stream' in requestParameters['createChartRequest'] && requestParameters['createChartRequest']['stream'] === true) {
            return new runtime.StreamApiResponse(response);
        }

        return new runtime.JSONApiResponse(response, (jsonValue) => ChartResponseFromJSON(jsonValue));
    }

    /**
     * Create charts.
     * Create a chart
     */
    async createChartsEndpoint(requestParameters: CreateChartsEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChartResponse | ReadableStream<any>> {
        const response = await this.createChartsEndpointRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
