/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.45
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AbcAPIErrorModel49,
  AbcAPIErrorModel50,
  AbcAPIErrorModel51,
  AbcAPIErrorModel52,
  AsknewsApiErrorsAPIErrorModel,
  ProfileResponse,
  ValidationErrorModel,
} from '../models/index';
import {
    AbcAPIErrorModel49FromJSON,
    AbcAPIErrorModel49ToJSON,
    AbcAPIErrorModel50FromJSON,
    AbcAPIErrorModel50ToJSON,
    AbcAPIErrorModel51FromJSON,
    AbcAPIErrorModel51ToJSON,
    AbcAPIErrorModel52FromJSON,
    AbcAPIErrorModel52ToJSON,
    AsknewsApiErrorsAPIErrorModelFromJSON,
    AsknewsApiErrorsAPIErrorModelToJSON,
    ProfileResponseFromJSON,
    ProfileResponseToJSON,
    ValidationErrorModelFromJSON,
    ValidationErrorModelToJSON,
} from '../models/index';

/**
 * 
 */
export class ProfileApi extends runtime.BaseAPI {

    /**
     * Get the current profile
     * Get the current user\'s profile
     */
    async getUserProfileRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProfileResponse> > {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/profiles/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);


        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileResponseFromJSON(jsonValue));
    }

    /**
     * Get the current profile
     * Get the current user\'s profile
     */
    async getUserProfile(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProfileResponse> {
        const response = await this.getUserProfileRaw(initOverrides);
        return await response.value();
    }

}
