/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.21.1
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AbcAPIErrorModel63
 */
export interface AbcAPIErrorModel63 {
    /**
     * 
     * @type {number}
     * @memberof AbcAPIErrorModel63
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof AbcAPIErrorModel63
     */
    detail: string;
}

/**
 * Check if a given object implements the AbcAPIErrorModel63 interface.
 */
export function instanceOfAbcAPIErrorModel63(value: object): value is AbcAPIErrorModel63 {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function AbcAPIErrorModel63FromJSON(json: any): AbcAPIErrorModel63 {
    return AbcAPIErrorModel63FromJSONTyped(json, false);
}

export function AbcAPIErrorModel63FromJSONTyped(json: any, ignoreDiscriminator: boolean): AbcAPIErrorModel63 {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'detail': json['detail'],
    };
}

export function AbcAPIErrorModel63ToJSON(json: any): AbcAPIErrorModel63 {
    return AbcAPIErrorModel63ToJSONTyped(json, false);
}

export function AbcAPIErrorModel63ToJSONTyped(value?: AbcAPIErrorModel63 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'detail': value['detail'],
    };
}

