/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.19.10
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AbcAPIErrorModel30
 */
export interface AbcAPIErrorModel30 {
    /**
     * 
     * @type {number}
     * @memberof AbcAPIErrorModel30
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof AbcAPIErrorModel30
     */
    detail: string;
}

/**
 * Check if a given object implements the AbcAPIErrorModel30 interface.
 */
export function instanceOfAbcAPIErrorModel30(value: object): value is AbcAPIErrorModel30 {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function AbcAPIErrorModel30FromJSON(json: any): AbcAPIErrorModel30 {
    return AbcAPIErrorModel30FromJSONTyped(json, false);
}

export function AbcAPIErrorModel30FromJSONTyped(json: any, ignoreDiscriminator: boolean): AbcAPIErrorModel30 {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'detail': json['detail'],
    };
}

export function AbcAPIErrorModel30ToJSON(json: any): AbcAPIErrorModel30 {
    return AbcAPIErrorModel30ToJSONTyped(json, false);
}

export function AbcAPIErrorModel30ToJSONTyped(value?: AbcAPIErrorModel30 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'detail': value['detail'],
    };
}

