/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.22.10
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AbcAPIErrorModel80
 */
export interface AbcAPIErrorModel80 {
    /**
     * 
     * @type {number}
     * @memberof AbcAPIErrorModel80
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof AbcAPIErrorModel80
     */
    detail: string;
}

/**
 * Check if a given object implements the AbcAPIErrorModel80 interface.
 */
export function instanceOfAbcAPIErrorModel80(value: object): value is AbcAPIErrorModel80 {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function AbcAPIErrorModel80FromJSON(json: any): AbcAPIErrorModel80 {
    return AbcAPIErrorModel80FromJSONTyped(json, false);
}

export function AbcAPIErrorModel80FromJSONTyped(json: any, ignoreDiscriminator: boolean): AbcAPIErrorModel80 {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'detail': json['detail'],
    };
}

export function AbcAPIErrorModel80ToJSON(json: any): AbcAPIErrorModel80 {
    return AbcAPIErrorModel80ToJSONTyped(json, false);
}

export function AbcAPIErrorModel80ToJSONTyped(value?: AbcAPIErrorModel80 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'detail': value['detail'],
    };
}

