/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.45
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AbcAPIErrorModel78
 */
export interface AbcAPIErrorModel78 {
    /**
     * 
     * @type {number}
     * @memberof AbcAPIErrorModel78
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof AbcAPIErrorModel78
     */
    detail: string;
}

/**
 * Check if a given object implements the AbcAPIErrorModel78 interface.
 */
export function instanceOfAbcAPIErrorModel78(value: object): value is AbcAPIErrorModel78 {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function AbcAPIErrorModel78FromJSON(json: any): AbcAPIErrorModel78 {
    return AbcAPIErrorModel78FromJSONTyped(json, false);
}

export function AbcAPIErrorModel78FromJSONTyped(json: any, ignoreDiscriminator: boolean): AbcAPIErrorModel78 {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'detail': json['detail'],
    };
}

export function AbcAPIErrorModel78ToJSON(json: any): AbcAPIErrorModel78 {
    return AbcAPIErrorModel78ToJSONTyped(json, false);
}

export function AbcAPIErrorModel78ToJSONTyped(value?: AbcAPIErrorModel78 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'detail': value['detail'],
    };
}

