/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.24.4
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AbcAPIErrorModel28
 */
export interface AbcAPIErrorModel28 {
    /**
     * 
     * @type {number}
     * @memberof AbcAPIErrorModel28
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof AbcAPIErrorModel28
     */
    detail: string;
}

/**
 * Check if a given object implements the AbcAPIErrorModel28 interface.
 */
export function instanceOfAbcAPIErrorModel28(value: object): value is AbcAPIErrorModel28 {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function AbcAPIErrorModel28FromJSON(json: any): AbcAPIErrorModel28 {
    return AbcAPIErrorModel28FromJSONTyped(json, false);
}

export function AbcAPIErrorModel28FromJSONTyped(json: any, ignoreDiscriminator: boolean): AbcAPIErrorModel28 {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'detail': json['detail'],
    };
}

export function AbcAPIErrorModel28ToJSON(json: any): AbcAPIErrorModel28 {
    return AbcAPIErrorModel28ToJSONTyped(json, false);
}

export function AbcAPIErrorModel28ToJSONTyped(value?: AbcAPIErrorModel28 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'detail': value['detail'],
    };
}

