/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.23.2
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AbcAPIErrorModel58
 */
export interface AbcAPIErrorModel58 {
    /**
     * 
     * @type {number}
     * @memberof AbcAPIErrorModel58
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof AbcAPIErrorModel58
     */
    detail: string;
}

/**
 * Check if a given object implements the AbcAPIErrorModel58 interface.
 */
export function instanceOfAbcAPIErrorModel58(value: object): value is AbcAPIErrorModel58 {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function AbcAPIErrorModel58FromJSON(json: any): AbcAPIErrorModel58 {
    return AbcAPIErrorModel58FromJSONTyped(json, false);
}

export function AbcAPIErrorModel58FromJSONTyped(json: any, ignoreDiscriminator: boolean): AbcAPIErrorModel58 {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'detail': json['detail'],
    };
}

export function AbcAPIErrorModel58ToJSON(json: any): AbcAPIErrorModel58 {
    return AbcAPIErrorModel58ToJSONTyped(json, false);
}

export function AbcAPIErrorModel58ToJSONTyped(value?: AbcAPIErrorModel58 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'detail': value['detail'],
    };
}

