/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.22.23
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AbcAPIErrorModel70
 */
export interface AbcAPIErrorModel70 {
    /**
     * 
     * @type {number}
     * @memberof AbcAPIErrorModel70
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof AbcAPIErrorModel70
     */
    detail: string;
}

/**
 * Check if a given object implements the AbcAPIErrorModel70 interface.
 */
export function instanceOfAbcAPIErrorModel70(value: object): value is AbcAPIErrorModel70 {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function AbcAPIErrorModel70FromJSON(json: any): AbcAPIErrorModel70 {
    return AbcAPIErrorModel70FromJSONTyped(json, false);
}

export function AbcAPIErrorModel70FromJSONTyped(json: any, ignoreDiscriminator: boolean): AbcAPIErrorModel70 {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'detail': json['detail'],
    };
}

export function AbcAPIErrorModel70ToJSON(json: any): AbcAPIErrorModel70 {
    return AbcAPIErrorModel70ToJSONTyped(json, false);
}

export function AbcAPIErrorModel70ToJSONTyped(value?: AbcAPIErrorModel70 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'detail': value['detail'],
    };
}

