/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AbcAPIErrorModel114
 */
export interface AbcAPIErrorModel114 {
    /**
     * 
     * @type {number}
     * @memberof AbcAPIErrorModel114
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof AbcAPIErrorModel114
     */
    detail: string;
}

/**
 * Check if a given object implements the AbcAPIErrorModel114 interface.
 */
export function instanceOfAbcAPIErrorModel114(value: object): value is AbcAPIErrorModel114 {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function AbcAPIErrorModel114FromJSON(json: any): AbcAPIErrorModel114 {
    return AbcAPIErrorModel114FromJSONTyped(json, false);
}

export function AbcAPIErrorModel114FromJSONTyped(json: any, ignoreDiscriminator: boolean): AbcAPIErrorModel114 {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'detail': json['detail'],
    };
}

export function AbcAPIErrorModel114ToJSON(json: any): AbcAPIErrorModel114 {
    return AbcAPIErrorModel114ToJSONTyped(json, false);
}

export function AbcAPIErrorModel114ToJSONTyped(value?: AbcAPIErrorModel114 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'detail': value['detail'],
    };
}

