/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.22.7
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AbcAPIErrorModel53
 */
export interface AbcAPIErrorModel53 {
    /**
     * 
     * @type {number}
     * @memberof AbcAPIErrorModel53
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof AbcAPIErrorModel53
     */
    detail: string;
}

/**
 * Check if a given object implements the AbcAPIErrorModel53 interface.
 */
export function instanceOfAbcAPIErrorModel53(value: object): value is AbcAPIErrorModel53 {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function AbcAPIErrorModel53FromJSON(json: any): AbcAPIErrorModel53 {
    return AbcAPIErrorModel53FromJSONTyped(json, false);
}

export function AbcAPIErrorModel53FromJSONTyped(json: any, ignoreDiscriminator: boolean): AbcAPIErrorModel53 {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'detail': json['detail'],
    };
}

export function AbcAPIErrorModel53ToJSON(json: any): AbcAPIErrorModel53 {
    return AbcAPIErrorModel53ToJSONTyped(json, false);
}

export function AbcAPIErrorModel53ToJSONTyped(value?: AbcAPIErrorModel53 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'detail': value['detail'],
    };
}

