/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.8.6
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Additional context to use for the forecast.
 * @export
 * @interface AdditionalContext
 */
export interface AdditionalContext {
}

/**
 * Check if a given object implements the AdditionalContext interface.
 */
export function instanceOfAdditionalContext(value: object): boolean {
    return true;
}

export function AdditionalContextFromJSON(json: any): AdditionalContext {
    return AdditionalContextFromJSONTyped(json, false);
}

export function AdditionalContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdditionalContext {
    return json;
}

export function AdditionalContextToJSON(value?: AdditionalContext | null): any {
    return value;
}

