/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.66
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnthropicInputJsonDelta1
 */
export interface AnthropicInputJsonDelta1 {
    /**
     * 
     * @type {string}
     * @memberof AnthropicInputJsonDelta1
     */
    type?: AnthropicInputJsonDelta1TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AnthropicInputJsonDelta1
     */
    partialJson: string;
}


/**
 * @export
 */
export const AnthropicInputJsonDelta1TypeEnum = {
    InputJsonDelta: 'input_json_delta'
} as const;
export type AnthropicInputJsonDelta1TypeEnum = typeof AnthropicInputJsonDelta1TypeEnum[keyof typeof AnthropicInputJsonDelta1TypeEnum];


/**
 * Check if a given object implements the AnthropicInputJsonDelta1 interface.
 */
export function instanceOfAnthropicInputJsonDelta1(value: object): value is AnthropicInputJsonDelta1 {
    if (!('partialJson' in value) || value['partialJson'] === undefined) return false;
    return true;
}

export function AnthropicInputJsonDelta1FromJSON(json: any): AnthropicInputJsonDelta1 {
    return AnthropicInputJsonDelta1FromJSONTyped(json, false);
}

export function AnthropicInputJsonDelta1FromJSONTyped(json: any, ignoreDiscriminator: boolean): AnthropicInputJsonDelta1 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'partialJson': json['partial_json'],
    };
}

export function AnthropicInputJsonDelta1ToJSON(json: any): AnthropicInputJsonDelta1 {
    return AnthropicInputJsonDelta1ToJSONTyped(json, false);
}

export function AnthropicInputJsonDelta1ToJSONTyped(value?: AnthropicInputJsonDelta1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'partial_json': value['partialJson'],
    };
}

