/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnthropicInputJsonDelta
 */
export interface AnthropicInputJsonDelta {
    /**
     * 
     * @type {string}
     * @memberof AnthropicInputJsonDelta
     */
    type?: AnthropicInputJsonDeltaTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AnthropicInputJsonDelta
     */
    partialJson: string;
}


/**
 * @export
 */
export const AnthropicInputJsonDeltaTypeEnum = {
    InputJsonDelta: 'input_json_delta'
} as const;
export type AnthropicInputJsonDeltaTypeEnum = typeof AnthropicInputJsonDeltaTypeEnum[keyof typeof AnthropicInputJsonDeltaTypeEnum];


/**
 * Check if a given object implements the AnthropicInputJsonDelta interface.
 */
export function instanceOfAnthropicInputJsonDelta(value: object): value is AnthropicInputJsonDelta {
    if (!('partialJson' in value) || value['partialJson'] === undefined) return false;
    return true;
}

export function AnthropicInputJsonDeltaFromJSON(json: any): AnthropicInputJsonDelta {
    return AnthropicInputJsonDeltaFromJSONTyped(json, false);
}

export function AnthropicInputJsonDeltaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnthropicInputJsonDelta {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'partialJson': json['partial_json'],
    };
}

export function AnthropicInputJsonDeltaToJSON(json: any): AnthropicInputJsonDelta {
    return AnthropicInputJsonDeltaToJSONTyped(json, false);
}

export function AnthropicInputJsonDeltaToJSONTyped(value?: AnthropicInputJsonDelta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'partial_json': value['partialJson'],
    };
}

