/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.66
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnthropicToolUseBlock1
 */
export interface AnthropicToolUseBlock1 {
    /**
     * 
     * @type {string}
     * @memberof AnthropicToolUseBlock1
     */
    type?: AnthropicToolUseBlock1TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AnthropicToolUseBlock1
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AnthropicToolUseBlock1
     */
    name: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AnthropicToolUseBlock1
     */
    input?: { [key: string]: any; };
}


/**
 * @export
 */
export const AnthropicToolUseBlock1TypeEnum = {
    ToolUse: 'tool_use'
} as const;
export type AnthropicToolUseBlock1TypeEnum = typeof AnthropicToolUseBlock1TypeEnum[keyof typeof AnthropicToolUseBlock1TypeEnum];


/**
 * Check if a given object implements the AnthropicToolUseBlock1 interface.
 */
export function instanceOfAnthropicToolUseBlock1(value: object): value is AnthropicToolUseBlock1 {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AnthropicToolUseBlock1FromJSON(json: any): AnthropicToolUseBlock1 {
    return AnthropicToolUseBlock1FromJSONTyped(json, false);
}

export function AnthropicToolUseBlock1FromJSONTyped(json: any, ignoreDiscriminator: boolean): AnthropicToolUseBlock1 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'id': json['id'],
        'name': json['name'],
        'input': json['input'] == null ? undefined : json['input'],
    };
}

export function AnthropicToolUseBlock1ToJSON(json: any): AnthropicToolUseBlock1 {
    return AnthropicToolUseBlock1ToJSONTyped(json, false);
}

export function AnthropicToolUseBlock1ToJSONTyped(value?: AnthropicToolUseBlock1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'name': value['name'],
        'input': value['input'],
    };
}

