/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnthropicThinkingBlock
 */
export interface AnthropicThinkingBlock {
    /**
     * 
     * @type {string}
     * @memberof AnthropicThinkingBlock
     */
    type?: AnthropicThinkingBlockTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AnthropicThinkingBlock
     */
    thinking?: string;
}


/**
 * @export
 */
export const AnthropicThinkingBlockTypeEnum = {
    Thinking: 'thinking'
} as const;
export type AnthropicThinkingBlockTypeEnum = typeof AnthropicThinkingBlockTypeEnum[keyof typeof AnthropicThinkingBlockTypeEnum];


/**
 * Check if a given object implements the AnthropicThinkingBlock interface.
 */
export function instanceOfAnthropicThinkingBlock(value: object): value is AnthropicThinkingBlock {
    return true;
}

export function AnthropicThinkingBlockFromJSON(json: any): AnthropicThinkingBlock {
    return AnthropicThinkingBlockFromJSONTyped(json, false);
}

export function AnthropicThinkingBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnthropicThinkingBlock {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'thinking': json['thinking'] == null ? undefined : json['thinking'],
    };
}

export function AnthropicThinkingBlockToJSON(json: any): AnthropicThinkingBlock {
    return AnthropicThinkingBlockToJSONTyped(json, false);
}

export function AnthropicThinkingBlockToJSONTyped(value?: AnthropicThinkingBlock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'thinking': value['thinking'],
    };
}

