/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.66
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnthropicThinkingDelta
 */
export interface AnthropicThinkingDelta {
    /**
     * 
     * @type {string}
     * @memberof AnthropicThinkingDelta
     */
    type?: AnthropicThinkingDeltaTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AnthropicThinkingDelta
     */
    thinking: string;
}


/**
 * @export
 */
export const AnthropicThinkingDeltaTypeEnum = {
    ThinkingDelta: 'thinking_delta'
} as const;
export type AnthropicThinkingDeltaTypeEnum = typeof AnthropicThinkingDeltaTypeEnum[keyof typeof AnthropicThinkingDeltaTypeEnum];


/**
 * Check if a given object implements the AnthropicThinkingDelta interface.
 */
export function instanceOfAnthropicThinkingDelta(value: object): value is AnthropicThinkingDelta {
    if (!('thinking' in value) || value['thinking'] === undefined) return false;
    return true;
}

export function AnthropicThinkingDeltaFromJSON(json: any): AnthropicThinkingDelta {
    return AnthropicThinkingDeltaFromJSONTyped(json, false);
}

export function AnthropicThinkingDeltaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnthropicThinkingDelta {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'thinking': json['thinking'],
    };
}

export function AnthropicThinkingDeltaToJSON(json: any): AnthropicThinkingDelta {
    return AnthropicThinkingDeltaToJSONTyped(json, false);
}

export function AnthropicThinkingDeltaToJSONTyped(value?: AnthropicThinkingDelta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'thinking': value['thinking'],
    };
}

