/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.22.7
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleHitItem } from './ArticleHitItem';
import {
    ArticleHitItemFromJSON,
    ArticleHitItemFromJSONTyped,
    ArticleHitItemToJSON,
    ArticleHitItemToJSONTyped,
} from './ArticleHitItem';

/**
 * 
 * @export
 * @interface ArticleHitsResponse
 */
export interface ArticleHitsResponse {
    /**
     * 
     * @type {Array<ArticleHitItem>}
     * @memberof ArticleHitsResponse
     */
    data: Array<ArticleHitItem>;
}

/**
 * Check if a given object implements the ArticleHitsResponse interface.
 */
export function instanceOfArticleHitsResponse(value: object): value is ArticleHitsResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ArticleHitsResponseFromJSON(json: any): ArticleHitsResponse {
    return ArticleHitsResponseFromJSONTyped(json, false);
}

export function ArticleHitsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleHitsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ArticleHitItemFromJSON)),
    };
}

export function ArticleHitsResponseToJSON(json: any): ArticleHitsResponse {
    return ArticleHitsResponseToJSONTyped(json, false);
}

export function ArticleHitsResponseToJSONTyped(value?: ArticleHitsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ArticleHitItemToJSON)),
    };
}

