/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.18.22
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Assets
 */
export interface Assets {
    /**
     * 
     * @type {Array<string>}
     * @memberof Assets
     */
    images?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Assets
     */
    videos?: Array<string> | null;
}

/**
 * Check if a given object implements the Assets interface.
 */
export function instanceOfAssets(value: object): value is Assets {
    return true;
}

export function AssetsFromJSON(json: any): Assets {
    return AssetsFromJSONTyped(json, false);
}

export function AssetsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Assets {
    if (json == null) {
        return json;
    }
    return {
        
        'images': json['images'] == null ? undefined : json['images'],
        'videos': json['videos'] == null ? undefined : json['videos'],
    };
}

export function AssetsToJSON(json: any): Assets {
    return AssetsToJSONTyped(json, false);
}

export function AssetsToJSONTyped(value?: Assets | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'images': value['images'],
        'videos': value['videos'],
    };
}

