/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.43
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Domain blacklist.This can be a single domain or a list of domains. For example, 'npr.org' or ['nature.com', 'npr.org']
 * @export
 * @interface BadDomainUrl2
 */
export interface BadDomainUrl2 {
}

/**
 * Check if a given object implements the BadDomainUrl2 interface.
 */
export function instanceOfBadDomainUrl2(value: object): value is BadDomainUrl2 {
    return true;
}

export function BadDomainUrl2FromJSON(json: any): BadDomainUrl2 {
    return BadDomainUrl2FromJSONTyped(json, false);
}

export function BadDomainUrl2FromJSONTyped(json: any, ignoreDiscriminator: boolean): BadDomainUrl2 {
    return json;
}

export function BadDomainUrl2ToJSON(json: any): BadDomainUrl2 {
    return BadDomainUrl2ToJSONTyped(json, false);
}

export function BadDomainUrl2ToJSONTyped(value?: BadDomainUrl2 | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

