/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.45
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlueskySourceParams
 */
export interface BlueskySourceParams {
    /**
     * 
     * @type {string}
     * @memberof BlueskySourceParams
     */
    query?: string | null;
}

/**
 * Check if a given object implements the BlueskySourceParams interface.
 */
export function instanceOfBlueskySourceParams(value: object): value is BlueskySourceParams {
    return true;
}

export function BlueskySourceParamsFromJSON(json: any): BlueskySourceParams {
    return BlueskySourceParamsFromJSONTyped(json, false);
}

export function BlueskySourceParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlueskySourceParams {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'] == null ? undefined : json['query'],
    };
}

export function BlueskySourceParamsToJSON(json: any): BlueskySourceParams {
    return BlueskySourceParamsToJSONTyped(json, false);
}

export function BlueskySourceParamsToJSONTyped(value?: BlueskySourceParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'query': value['query'],
    };
}

