/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.27
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SeriesConfig } from './SeriesConfig';
import {
    SeriesConfigFromJSON,
    SeriesConfigFromJSONTyped,
    SeriesConfigToJSON,
    SeriesConfigToJSONTyped,
} from './SeriesConfig';

/**
 * 
 * @export
 * @interface ChartParameters
 */
export interface ChartParameters {
    /**
     * The type of chart to create
     * @type {string}
     * @memberof ChartParameters
     */
    chartType: ChartParametersChartTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ChartParameters
     */
    title?: string | null;
    /**
     * The series configurations for the chart
     * @type {Array<SeriesConfig>}
     * @memberof ChartParameters
     */
    series: Array<SeriesConfig>;
}


/**
 * @export
 */
export const ChartParametersChartTypeEnum = {
    Line: 'line',
    Bar: 'bar',
    BarPct: 'bar_pct'
} as const;
export type ChartParametersChartTypeEnum = typeof ChartParametersChartTypeEnum[keyof typeof ChartParametersChartTypeEnum];


/**
 * Check if a given object implements the ChartParameters interface.
 */
export function instanceOfChartParameters(value: object): value is ChartParameters {
    if (!('chartType' in value) || value['chartType'] === undefined) return false;
    if (!('series' in value) || value['series'] === undefined) return false;
    return true;
}

export function ChartParametersFromJSON(json: any): ChartParameters {
    return ChartParametersFromJSONTyped(json, false);
}

export function ChartParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChartParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'chartType': json['chart_type'],
        'title': json['title'] == null ? undefined : json['title'],
        'series': ((json['series'] as Array<any>).map(SeriesConfigFromJSON)),
    };
}

export function ChartParametersToJSON(json: any): ChartParameters {
    return ChartParametersToJSONTyped(json, false);
}

export function ChartParametersToJSONTyped(value?: ChartParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chart_type': value['chartType'],
        'title': value['title'],
        'series': ((value['series'] as Array<any>).map(SeriesConfigToJSON)),
    };
}

