/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Delta1 } from './Delta1';
import {
    Delta1FromJSON,
    Delta1FromJSONTyped,
    Delta1ToJSON,
    Delta1ToJSONTyped,
} from './Delta1';

/**
 * 
 * @export
 * @interface ContentBlockDeltaEvent
 */
export interface ContentBlockDeltaEvent {
    /**
     * 
     * @type {string}
     * @memberof ContentBlockDeltaEvent
     */
    type?: ContentBlockDeltaEventTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ContentBlockDeltaEvent
     */
    index: number;
    /**
     * 
     * @type {Delta1}
     * @memberof ContentBlockDeltaEvent
     */
    delta: Delta1;
}


/**
 * @export
 */
export const ContentBlockDeltaEventTypeEnum = {
    ContentBlockDelta: 'content_block_delta'
} as const;
export type ContentBlockDeltaEventTypeEnum = typeof ContentBlockDeltaEventTypeEnum[keyof typeof ContentBlockDeltaEventTypeEnum];


/**
 * Check if a given object implements the ContentBlockDeltaEvent interface.
 */
export function instanceOfContentBlockDeltaEvent(value: object): value is ContentBlockDeltaEvent {
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('delta' in value) || value['delta'] === undefined) return false;
    return true;
}

export function ContentBlockDeltaEventFromJSON(json: any): ContentBlockDeltaEvent {
    return ContentBlockDeltaEventFromJSONTyped(json, false);
}

export function ContentBlockDeltaEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentBlockDeltaEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'index': json['index'],
        'delta': Delta1FromJSON(json['delta']),
    };
}

export function ContentBlockDeltaEventToJSON(json: any): ContentBlockDeltaEvent {
    return ContentBlockDeltaEventToJSONTyped(json, false);
}

export function ContentBlockDeltaEventToJSONTyped(value?: ContentBlockDeltaEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'index': value['index'],
        'delta': Delta1ToJSON(value['delta']),
    };
}

