/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.66
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Delta } from './Delta';
import {
    DeltaFromJSON,
    DeltaFromJSONTyped,
    DeltaToJSON,
    DeltaToJSONTyped,
} from './Delta';

/**
 * 
 * @export
 * @interface ContentBlockDeltaEvent1
 */
export interface ContentBlockDeltaEvent1 {
    /**
     * 
     * @type {string}
     * @memberof ContentBlockDeltaEvent1
     */
    type?: ContentBlockDeltaEvent1TypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ContentBlockDeltaEvent1
     */
    index: number;
    /**
     * 
     * @type {Delta}
     * @memberof ContentBlockDeltaEvent1
     */
    delta: Delta;
}


/**
 * @export
 */
export const ContentBlockDeltaEvent1TypeEnum = {
    ContentBlockDelta: 'content_block_delta'
} as const;
export type ContentBlockDeltaEvent1TypeEnum = typeof ContentBlockDeltaEvent1TypeEnum[keyof typeof ContentBlockDeltaEvent1TypeEnum];


/**
 * Check if a given object implements the ContentBlockDeltaEvent1 interface.
 */
export function instanceOfContentBlockDeltaEvent1(value: object): value is ContentBlockDeltaEvent1 {
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('delta' in value) || value['delta'] === undefined) return false;
    return true;
}

export function ContentBlockDeltaEvent1FromJSON(json: any): ContentBlockDeltaEvent1 {
    return ContentBlockDeltaEvent1FromJSONTyped(json, false);
}

export function ContentBlockDeltaEvent1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentBlockDeltaEvent1 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'index': json['index'],
        'delta': DeltaFromJSON(json['delta']),
    };
}

export function ContentBlockDeltaEvent1ToJSON(json: any): ContentBlockDeltaEvent1 {
    return ContentBlockDeltaEvent1ToJSONTyped(json, false);
}

export function ContentBlockDeltaEvent1ToJSONTyped(value?: ContentBlockDeltaEvent1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'index': value['index'],
        'delta': DeltaToJSON(value['delta']),
    };
}

