/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.24.4
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Continents to filter by.
 * @export
 * @interface Continent
 */
export interface Continent {
}

/**
 * Check if a given object implements the Continent interface.
 */
export function instanceOfContinent(value: object): value is Continent {
    return true;
}

export function ContinentFromJSON(json: any): Continent {
    return ContinentFromJSONTyped(json, false);
}

export function ContinentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Continent {
    return json;
}

export function ContinentToJSON(json: any): Continent {
    return ContinentToJSONTyped(json, false);
}

export function ContinentToJSONTyped(value?: Continent | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

