/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.45
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CountResponse
 */
export interface CountResponse {
    /**
     * 
     * @type {number}
     * @memberof CountResponse
     */
    count: number;
}

/**
 * Check if a given object implements the CountResponse interface.
 */
export function instanceOfCountResponse(value: object): value is CountResponse {
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function CountResponseFromJSON(json: any): CountResponse {
    return CountResponseFromJSONTyped(json, false);
}

export function CountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CountResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
    };
}

export function CountResponseToJSON(json: any): CountResponse {
    return CountResponseToJSONTyped(json, false);
}

export function CountResponseToJSONTyped(value?: CountResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
    };
}

