/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.66
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDeepNewsResponseUsage2
 */
export interface CreateDeepNewsResponseUsage2 {
    /**
     * 
     * @type {number}
     * @memberof CreateDeepNewsResponseUsage2
     */
    promptTokens: number;
    /**
     * 
     * @type {number}
     * @memberof CreateDeepNewsResponseUsage2
     */
    completionTokens: number;
    /**
     * 
     * @type {number}
     * @memberof CreateDeepNewsResponseUsage2
     */
    totalTokens: number;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof CreateDeepNewsResponseUsage2
     */
    toolUsage?: { [key: string]: number; } | null;
}

/**
 * Check if a given object implements the CreateDeepNewsResponseUsage2 interface.
 */
export function instanceOfCreateDeepNewsResponseUsage2(value: object): value is CreateDeepNewsResponseUsage2 {
    if (!('promptTokens' in value) || value['promptTokens'] === undefined) return false;
    if (!('completionTokens' in value) || value['completionTokens'] === undefined) return false;
    if (!('totalTokens' in value) || value['totalTokens'] === undefined) return false;
    return true;
}

export function CreateDeepNewsResponseUsage2FromJSON(json: any): CreateDeepNewsResponseUsage2 {
    return CreateDeepNewsResponseUsage2FromJSONTyped(json, false);
}

export function CreateDeepNewsResponseUsage2FromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDeepNewsResponseUsage2 {
    if (json == null) {
        return json;
    }
    return {
        
        'promptTokens': json['prompt_tokens'],
        'completionTokens': json['completion_tokens'],
        'totalTokens': json['total_tokens'],
        'toolUsage': json['tool_usage'] == null ? undefined : json['tool_usage'],
    };
}

export function CreateDeepNewsResponseUsage2ToJSON(json: any): CreateDeepNewsResponseUsage2 {
    return CreateDeepNewsResponseUsage2ToJSONTyped(json, false);
}

export function CreateDeepNewsResponseUsage2ToJSONTyped(value?: CreateDeepNewsResponseUsage2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt_tokens': value['promptTokens'],
        'completion_tokens': value['completionTokens'],
        'total_tokens': value['totalTokens'],
        'tool_usage': value['toolUsage'],
    };
}

