/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.43
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateDeepNewsRequestMessage1 } from './CreateDeepNewsRequestMessage1';
import {
    CreateDeepNewsRequestMessage1FromJSON,
    CreateDeepNewsRequestMessage1FromJSONTyped,
    CreateDeepNewsRequestMessage1ToJSON,
    CreateDeepNewsRequestMessage1ToJSONTyped,
} from './CreateDeepNewsRequestMessage1';

/**
 * 
 * @export
 * @interface CreateDeepNewsResponseStreamChunkChoice1
 */
export interface CreateDeepNewsResponseStreamChunkChoice1 {
    /**
     * 
     * @type {number}
     * @memberof CreateDeepNewsResponseStreamChunkChoice1
     */
    index: number;
    /**
     * 
     * @type {CreateDeepNewsRequestMessage1}
     * @memberof CreateDeepNewsResponseStreamChunkChoice1
     */
    delta: CreateDeepNewsRequestMessage1;
    /**
     * 
     * @type {string}
     * @memberof CreateDeepNewsResponseStreamChunkChoice1
     */
    finishReason?: string | null;
}

/**
 * Check if a given object implements the CreateDeepNewsResponseStreamChunkChoice1 interface.
 */
export function instanceOfCreateDeepNewsResponseStreamChunkChoice1(value: object): value is CreateDeepNewsResponseStreamChunkChoice1 {
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('delta' in value) || value['delta'] === undefined) return false;
    return true;
}

export function CreateDeepNewsResponseStreamChunkChoice1FromJSON(json: any): CreateDeepNewsResponseStreamChunkChoice1 {
    return CreateDeepNewsResponseStreamChunkChoice1FromJSONTyped(json, false);
}

export function CreateDeepNewsResponseStreamChunkChoice1FromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDeepNewsResponseStreamChunkChoice1 {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'],
        'delta': CreateDeepNewsRequestMessage1FromJSON(json['delta']),
        'finishReason': json['finish_reason'] == null ? undefined : json['finish_reason'],
    };
}

export function CreateDeepNewsResponseStreamChunkChoice1ToJSON(json: any): CreateDeepNewsResponseStreamChunkChoice1 {
    return CreateDeepNewsResponseStreamChunkChoice1ToJSONTyped(json, false);
}

export function CreateDeepNewsResponseStreamChunkChoice1ToJSONTyped(value?: CreateDeepNewsResponseStreamChunkChoice1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index': value['index'],
        'delta': CreateDeepNewsRequestMessage1ToJSON(value['delta']),
        'finish_reason': value['finishReason'],
    };
}

