/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.18.2
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateDeepNewsResponseStreamChunkChoice } from './CreateDeepNewsResponseStreamChunkChoice';
import {
    CreateDeepNewsResponseStreamChunkChoiceFromJSON,
    CreateDeepNewsResponseStreamChunkChoiceFromJSONTyped,
    CreateDeepNewsResponseStreamChunkChoiceToJSON,
} from './CreateDeepNewsResponseStreamChunkChoice';
import type { CreateDeepNewsResponseUsage } from './CreateDeepNewsResponseUsage';
import {
    CreateDeepNewsResponseUsageFromJSON,
    CreateDeepNewsResponseUsageFromJSONTyped,
    CreateDeepNewsResponseUsageToJSON,
} from './CreateDeepNewsResponseUsage';

/**
 * 
 * @export
 * @interface CreateDeepNewsResponseStreamChunk
 */
export interface CreateDeepNewsResponseStreamChunk {
    /**
     * 
     * @type {string}
     * @memberof CreateDeepNewsResponseStreamChunk
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof CreateDeepNewsResponseStreamChunk
     */
    created: number;
    /**
     * 
     * @type {string}
     * @memberof CreateDeepNewsResponseStreamChunk
     */
    object?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDeepNewsResponseStreamChunk
     */
    model?: string;
    /**
     * 
     * @type {CreateDeepNewsResponseUsage}
     * @memberof CreateDeepNewsResponseStreamChunk
     */
    usage: CreateDeepNewsResponseUsage;
    /**
     * 
     * @type {Array<CreateDeepNewsResponseStreamChunkChoice>}
     * @memberof CreateDeepNewsResponseStreamChunk
     */
    choices: Array<CreateDeepNewsResponseStreamChunkChoice>;
}

/**
 * Check if a given object implements the CreateDeepNewsResponseStreamChunk interface.
 */
export function instanceOfCreateDeepNewsResponseStreamChunk(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('created' in value)) return false;
    if (!('usage' in value)) return false;
    if (!('choices' in value)) return false;
    return true;
}

export function CreateDeepNewsResponseStreamChunkFromJSON(json: any): CreateDeepNewsResponseStreamChunk {
    return CreateDeepNewsResponseStreamChunkFromJSONTyped(json, false);
}

export function CreateDeepNewsResponseStreamChunkFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDeepNewsResponseStreamChunk {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'created': json['created'],
        'object': json['object'] == null ? undefined : json['object'],
        'model': json['model'] == null ? undefined : json['model'],
        'usage': CreateDeepNewsResponseUsageFromJSON(json['usage']),
        'choices': ((json['choices'] as Array<any>).map(CreateDeepNewsResponseStreamChunkChoiceFromJSON)),
    };
}

export function CreateDeepNewsResponseStreamChunkToJSON(value?: CreateDeepNewsResponseStreamChunk | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'created': value['created'],
        'object': value['object'],
        'model': value['model'],
        'usage': CreateDeepNewsResponseUsageToJSON(value['usage']),
        'choices': ((value['choices'] as Array<any>).map(CreateDeepNewsResponseStreamChunkChoiceToJSON)),
    };
}

