/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.18.19
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateDeepNewsRequestMessage1 } from './CreateDeepNewsRequestMessage1';
import {
    CreateDeepNewsRequestMessage1FromJSON,
    CreateDeepNewsRequestMessage1FromJSONTyped,
    CreateDeepNewsRequestMessage1ToJSON,
} from './CreateDeepNewsRequestMessage1';

/**
 * 
 * @export
 * @interface CreateDeepNewsResponseChoice1
 */
export interface CreateDeepNewsResponseChoice1 {
    /**
     * 
     * @type {number}
     * @memberof CreateDeepNewsResponseChoice1
     */
    index: number;
    /**
     * 
     * @type {CreateDeepNewsRequestMessage1}
     * @memberof CreateDeepNewsResponseChoice1
     */
    message: CreateDeepNewsRequestMessage1;
    /**
     * 
     * @type {string}
     * @memberof CreateDeepNewsResponseChoice1
     */
    finishReason?: string;
}

/**
 * Check if a given object implements the CreateDeepNewsResponseChoice1 interface.
 */
export function instanceOfCreateDeepNewsResponseChoice1(value: object): boolean {
    if (!('index' in value)) return false;
    if (!('message' in value)) return false;
    return true;
}

export function CreateDeepNewsResponseChoice1FromJSON(json: any): CreateDeepNewsResponseChoice1 {
    return CreateDeepNewsResponseChoice1FromJSONTyped(json, false);
}

export function CreateDeepNewsResponseChoice1FromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDeepNewsResponseChoice1 {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'],
        'message': CreateDeepNewsRequestMessage1FromJSON(json['message']),
        'finishReason': json['finish_reason'] == null ? undefined : json['finish_reason'],
    };
}

export function CreateDeepNewsResponseChoice1ToJSON(value?: CreateDeepNewsResponseChoice1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'index': value['index'],
        'message': CreateDeepNewsRequestMessage1ToJSON(value['message']),
        'finish_reason': value['finishReason'],
    };
}

