/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.19.6
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateChatCompletionRequestMessage1
 */
export interface CreateChatCompletionRequestMessage1 {
    /**
     * 
     * @type {string}
     * @memberof CreateChatCompletionRequestMessage1
     */
    role: string;
    /**
     * 
     * @type {string}
     * @memberof CreateChatCompletionRequestMessage1
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof CreateChatCompletionRequestMessage1
     */
    name?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateChatCompletionRequestMessage1
     */
    functionCall?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the CreateChatCompletionRequestMessage1 interface.
 */
export function instanceOfCreateChatCompletionRequestMessage1(value: object): value is CreateChatCompletionRequestMessage1 {
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CreateChatCompletionRequestMessage1FromJSON(json: any): CreateChatCompletionRequestMessage1 {
    return CreateChatCompletionRequestMessage1FromJSONTyped(json, false);
}

export function CreateChatCompletionRequestMessage1FromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCompletionRequestMessage1 {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'],
        'content': json['content'],
        'name': json['name'] == null ? undefined : json['name'],
        'functionCall': json['function_call'] == null ? undefined : json['function_call'],
    };
}

export function CreateChatCompletionRequestMessage1ToJSON(json: any): CreateChatCompletionRequestMessage1 {
    return CreateChatCompletionRequestMessage1ToJSONTyped(json, false);
}

export function CreateChatCompletionRequestMessage1ToJSONTyped(value?: CreateChatCompletionRequestMessage1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
        'content': value['content'],
        'name': value['name'],
        'function_call': value['functionCall'],
    };
}

