/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.43
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeepNewsModel } from './DeepNewsModel';
import {
    DeepNewsModelFromJSON,
    DeepNewsModelFromJSONTyped,
    DeepNewsModelToJSON,
    DeepNewsModelToJSONTyped,
} from './DeepNewsModel';

/**
 * The model to use for DeepNews research. Defaults to claude-sonnet-4-5-20250929.
 * @export
 * @interface CreateDeepNewsRequestModel
 */
export interface CreateDeepNewsRequestModel {
}

/**
 * Check if a given object implements the CreateDeepNewsRequestModel interface.
 */
export function instanceOfCreateDeepNewsRequestModel(value: object): value is CreateDeepNewsRequestModel {
    return true;
}

export function CreateDeepNewsRequestModelFromJSON(json: any): CreateDeepNewsRequestModel {
    return CreateDeepNewsRequestModelFromJSONTyped(json, false);
}

export function CreateDeepNewsRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDeepNewsRequestModel {
    return json;
}

export function CreateDeepNewsRequestModelToJSON(json: any): CreateDeepNewsRequestModel {
    return CreateDeepNewsRequestModelToJSONTyped(json, false);
}

export function CreateDeepNewsRequestModelToJSONTyped(value?: CreateDeepNewsRequestModel | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

