/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.8.6
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateChatCompletionResponseUsage2
 */
export interface CreateChatCompletionResponseUsage2 {
    /**
     * 
     * @type {number}
     * @memberof CreateChatCompletionResponseUsage2
     */
    promptTokens: number;
    /**
     * 
     * @type {number}
     * @memberof CreateChatCompletionResponseUsage2
     */
    completionTokens: number;
    /**
     * 
     * @type {number}
     * @memberof CreateChatCompletionResponseUsage2
     */
    totalTokens: number;
}

/**
 * Check if a given object implements the CreateChatCompletionResponseUsage2 interface.
 */
export function instanceOfCreateChatCompletionResponseUsage2(value: object): boolean {
    if (!('promptTokens' in value)) return false;
    if (!('completionTokens' in value)) return false;
    if (!('totalTokens' in value)) return false;
    return true;
}

export function CreateChatCompletionResponseUsage2FromJSON(json: any): CreateChatCompletionResponseUsage2 {
    return CreateChatCompletionResponseUsage2FromJSONTyped(json, false);
}

export function CreateChatCompletionResponseUsage2FromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCompletionResponseUsage2 {
    if (json == null) {
        return json;
    }
    return {
        
        'promptTokens': json['prompt_tokens'],
        'completionTokens': json['completion_tokens'],
        'totalTokens': json['total_tokens'],
    };
}

export function CreateChatCompletionResponseUsage2ToJSON(value?: CreateChatCompletionResponseUsage2 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'prompt_tokens': value['promptTokens'],
        'completion_tokens': value['completionTokens'],
        'total_tokens': value['totalTokens'],
    };
}

