/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchResponseDictItem1 } from './SearchResponseDictItem1';
import {
    SearchResponseDictItem1FromJSON,
    SearchResponseDictItem1FromJSONTyped,
    SearchResponseDictItem1ToJSON,
    SearchResponseDictItem1ToJSONTyped,
} from './SearchResponseDictItem1';

/**
 * 
 * @export
 * @interface CreateDeepNewsResponseStreamSourcesNewsSource1
 */
export interface CreateDeepNewsResponseStreamSourcesNewsSource1 {
    /**
     * 
     * @type {string}
     * @memberof CreateDeepNewsResponseStreamSourcesNewsSource1
     */
    kind?: CreateDeepNewsResponseStreamSourcesNewsSource1KindEnum;
    /**
     * 
     * @type {SearchResponseDictItem1}
     * @memberof CreateDeepNewsResponseStreamSourcesNewsSource1
     */
    data: SearchResponseDictItem1;
}


/**
 * @export
 */
export const CreateDeepNewsResponseStreamSourcesNewsSource1KindEnum = {
    News: 'news'
} as const;
export type CreateDeepNewsResponseStreamSourcesNewsSource1KindEnum = typeof CreateDeepNewsResponseStreamSourcesNewsSource1KindEnum[keyof typeof CreateDeepNewsResponseStreamSourcesNewsSource1KindEnum];


/**
 * Check if a given object implements the CreateDeepNewsResponseStreamSourcesNewsSource1 interface.
 */
export function instanceOfCreateDeepNewsResponseStreamSourcesNewsSource1(value: object): value is CreateDeepNewsResponseStreamSourcesNewsSource1 {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CreateDeepNewsResponseStreamSourcesNewsSource1FromJSON(json: any): CreateDeepNewsResponseStreamSourcesNewsSource1 {
    return CreateDeepNewsResponseStreamSourcesNewsSource1FromJSONTyped(json, false);
}

export function CreateDeepNewsResponseStreamSourcesNewsSource1FromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDeepNewsResponseStreamSourcesNewsSource1 {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'] == null ? undefined : json['kind'],
        'data': SearchResponseDictItem1FromJSON(json['data']),
    };
}

export function CreateDeepNewsResponseStreamSourcesNewsSource1ToJSON(json: any): CreateDeepNewsResponseStreamSourcesNewsSource1 {
    return CreateDeepNewsResponseStreamSourcesNewsSource1ToJSONTyped(json, false);
}

export function CreateDeepNewsResponseStreamSourcesNewsSource1ToJSONTyped(value?: CreateDeepNewsResponseStreamSourcesNewsSource1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'data': SearchResponseDictItem1ToJSON(value['data']),
    };
}

