/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebSearchResult2 } from './WebSearchResult2';
import {
    WebSearchResult2FromJSON,
    WebSearchResult2FromJSONTyped,
    WebSearchResult2ToJSON,
    WebSearchResult2ToJSONTyped,
} from './WebSearchResult2';

/**
 * 
 * @export
 * @interface CreateDeepNewsResponseStreamSourcesWebSource1
 */
export interface CreateDeepNewsResponseStreamSourcesWebSource1 {
    /**
     * 
     * @type {string}
     * @memberof CreateDeepNewsResponseStreamSourcesWebSource1
     */
    kind?: CreateDeepNewsResponseStreamSourcesWebSource1KindEnum;
    /**
     * 
     * @type {WebSearchResult2}
     * @memberof CreateDeepNewsResponseStreamSourcesWebSource1
     */
    data: WebSearchResult2;
}


/**
 * @export
 */
export const CreateDeepNewsResponseStreamSourcesWebSource1KindEnum = {
    Web: 'web'
} as const;
export type CreateDeepNewsResponseStreamSourcesWebSource1KindEnum = typeof CreateDeepNewsResponseStreamSourcesWebSource1KindEnum[keyof typeof CreateDeepNewsResponseStreamSourcesWebSource1KindEnum];


/**
 * Check if a given object implements the CreateDeepNewsResponseStreamSourcesWebSource1 interface.
 */
export function instanceOfCreateDeepNewsResponseStreamSourcesWebSource1(value: object): value is CreateDeepNewsResponseStreamSourcesWebSource1 {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CreateDeepNewsResponseStreamSourcesWebSource1FromJSON(json: any): CreateDeepNewsResponseStreamSourcesWebSource1 {
    return CreateDeepNewsResponseStreamSourcesWebSource1FromJSONTyped(json, false);
}

export function CreateDeepNewsResponseStreamSourcesWebSource1FromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDeepNewsResponseStreamSourcesWebSource1 {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'] == null ? undefined : json['kind'],
        'data': WebSearchResult2FromJSON(json['data']),
    };
}

export function CreateDeepNewsResponseStreamSourcesWebSource1ToJSON(json: any): CreateDeepNewsResponseStreamSourcesWebSource1 {
    return CreateDeepNewsResponseStreamSourcesWebSource1ToJSONTyped(json, false);
}

export function CreateDeepNewsResponseStreamSourcesWebSource1ToJSONTyped(value?: CreateDeepNewsResponseStreamSourcesWebSource1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'data': WebSearchResult2ToJSON(value['data']),
    };
}

