/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.22.7
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateChatCompletionResponseStream } from './CreateChatCompletionResponseStream';
import {
    CreateChatCompletionResponseStreamFromJSON,
    CreateChatCompletionResponseStreamFromJSONTyped,
    CreateChatCompletionResponseStreamToJSON,
    CreateChatCompletionResponseStreamToJSONTyped,
} from './CreateChatCompletionResponseStream';
import type { CreateChatCompletionResponseUsage1 } from './CreateChatCompletionResponseUsage1';
import {
    CreateChatCompletionResponseUsage1FromJSON,
    CreateChatCompletionResponseUsage1FromJSONTyped,
    CreateChatCompletionResponseUsage1ToJSON,
    CreateChatCompletionResponseUsage1ToJSONTyped,
} from './CreateChatCompletionResponseUsage1';
import type { CreateChatCompletionResponse } from './CreateChatCompletionResponse';
import {
    CreateChatCompletionResponseFromJSON,
    CreateChatCompletionResponseFromJSONTyped,
    CreateChatCompletionResponseToJSON,
    CreateChatCompletionResponseToJSONTyped,
} from './CreateChatCompletionResponse';
import type { CreateChatCompletionResponseUsage } from './CreateChatCompletionResponseUsage';
import {
    CreateChatCompletionResponseUsageFromJSON,
    CreateChatCompletionResponseUsageFromJSONTyped,
    CreateChatCompletionResponseUsageToJSON,
    CreateChatCompletionResponseUsageToJSONTyped,
} from './CreateChatCompletionResponseUsage';
import type { CreateChatCompletionResponseChoice1 } from './CreateChatCompletionResponseChoice1';
import {
    CreateChatCompletionResponseChoice1FromJSON,
    CreateChatCompletionResponseChoice1FromJSONTyped,
    CreateChatCompletionResponseChoice1ToJSON,
    CreateChatCompletionResponseChoice1ToJSONTyped,
} from './CreateChatCompletionResponseChoice1';
import type { CreateChatCompletionResponseChoice } from './CreateChatCompletionResponseChoice';
import {
    CreateChatCompletionResponseChoiceFromJSON,
    CreateChatCompletionResponseChoiceFromJSONTyped,
    CreateChatCompletionResponseChoiceToJSON,
    CreateChatCompletionResponseChoiceToJSONTyped,
} from './CreateChatCompletionResponseChoice';

/**
 * 
 * @export
 * @interface CreateChatCompletionResponse1
 */
export interface CreateChatCompletionResponse1 {
    /**
     * 
     * @type {string}
     * @memberof CreateChatCompletionResponse1
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof CreateChatCompletionResponse1
     */
    created: number;
    /**
     * 
     * @type {string}
     * @memberof CreateChatCompletionResponse1
     */
    object?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateChatCompletionResponse1
     */
    model?: string;
    /**
     * 
     * @type {CreateChatCompletionResponseUsage1}
     * @memberof CreateChatCompletionResponse1
     */
    usage: CreateChatCompletionResponseUsage1;
    /**
     * 
     * @type {Array<CreateChatCompletionResponseChoice1>}
     * @memberof CreateChatCompletionResponse1
     */
    choices: Array<CreateChatCompletionResponseChoice1>;
}

/**
 * Check if a given object implements the CreateChatCompletionResponse1 interface.
 */
export function instanceOfCreateChatCompletionResponse1(value: object): value is CreateChatCompletionResponse1 {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('usage' in value) || value['usage'] === undefined) return false;
    if (!('choices' in value) || value['choices'] === undefined) return false;
    return true;
}

export function CreateChatCompletionResponse1FromJSON(json: any): CreateChatCompletionResponse1 {
    return CreateChatCompletionResponse1FromJSONTyped(json, false);
}

export function CreateChatCompletionResponse1FromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCompletionResponse1 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'created': json['created'],
        'object': json['object'] == null ? undefined : json['object'],
        'model': json['model'] == null ? undefined : json['model'],
        'usage': CreateChatCompletionResponseUsage1FromJSON(json['usage']),
        'choices': ((json['choices'] as Array<any>).map(CreateChatCompletionResponseChoice1FromJSON)),
    };
}

export function CreateChatCompletionResponse1ToJSON(json: any): CreateChatCompletionResponse1 {
    return CreateChatCompletionResponse1ToJSONTyped(json, false);
}

export function CreateChatCompletionResponse1ToJSONTyped(value?: CreateChatCompletionResponse1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'created': value['created'],
        'object': value['object'],
        'model': value['model'],
        'usage': CreateChatCompletionResponseUsage1ToJSON(value['usage']),
        'choices': ((value['choices'] as Array<any>).map(CreateChatCompletionResponseChoice1ToJSON)),
    };
}

