/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.18.19
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateDeepNewsResponseChoice } from './CreateDeepNewsResponseChoice';
import {
    CreateDeepNewsResponseChoiceFromJSON,
    CreateDeepNewsResponseChoiceFromJSONTyped,
    CreateDeepNewsResponseChoiceToJSON,
} from './CreateDeepNewsResponseChoice';
import type { CreateDeepNewsResponseUsage } from './CreateDeepNewsResponseUsage';
import {
    CreateDeepNewsResponseUsageFromJSON,
    CreateDeepNewsResponseUsageFromJSONTyped,
    CreateDeepNewsResponseUsageToJSON,
} from './CreateDeepNewsResponseUsage';
import type { DeepNewsResponseSources } from './DeepNewsResponseSources';
import {
    DeepNewsResponseSourcesFromJSON,
    DeepNewsResponseSourcesFromJSONTyped,
    DeepNewsResponseSourcesToJSON,
} from './DeepNewsResponseSources';

/**
 * 
 * @export
 * @interface CreateDeepNewsResponse
 */
export interface CreateDeepNewsResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateDeepNewsResponse
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof CreateDeepNewsResponse
     */
    created: number;
    /**
     * 
     * @type {string}
     * @memberof CreateDeepNewsResponse
     */
    object?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDeepNewsResponse
     */
    model?: string;
    /**
     * 
     * @type {CreateDeepNewsResponseUsage}
     * @memberof CreateDeepNewsResponse
     */
    usage: CreateDeepNewsResponseUsage;
    /**
     * 
     * @type {Array<CreateDeepNewsResponseChoice>}
     * @memberof CreateDeepNewsResponse
     */
    choices: Array<CreateDeepNewsResponseChoice>;
    /**
     * 
     * @type {DeepNewsResponseSources}
     * @memberof CreateDeepNewsResponse
     */
    sources: DeepNewsResponseSources;
}

/**
 * Check if a given object implements the CreateDeepNewsResponse interface.
 */
export function instanceOfCreateDeepNewsResponse(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('created' in value)) return false;
    if (!('usage' in value)) return false;
    if (!('choices' in value)) return false;
    if (!('sources' in value)) return false;
    return true;
}

export function CreateDeepNewsResponseFromJSON(json: any): CreateDeepNewsResponse {
    return CreateDeepNewsResponseFromJSONTyped(json, false);
}

export function CreateDeepNewsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDeepNewsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'created': json['created'],
        'object': json['object'] == null ? undefined : json['object'],
        'model': json['model'] == null ? undefined : json['model'],
        'usage': CreateDeepNewsResponseUsageFromJSON(json['usage']),
        'choices': ((json['choices'] as Array<any>).map(CreateDeepNewsResponseChoiceFromJSON)),
        'sources': DeepNewsResponseSourcesFromJSON(json['sources']),
    };
}

export function CreateDeepNewsResponseToJSON(value?: CreateDeepNewsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'created': value['created'],
        'object': value['object'],
        'model': value['model'],
        'usage': CreateDeepNewsResponseUsageToJSON(value['usage']),
        'choices': ((value['choices'] as Array<any>).map(CreateDeepNewsResponseChoiceToJSON)),
        'sources': DeepNewsResponseSourcesToJSON(value['sources']),
    };
}

