/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.28
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Source } from './Source';
import {
    SourceFromJSON,
    SourceFromJSONTyped,
    SourceToJSON,
    SourceToJSONTyped,
} from './Source';

/**
 * 
 * @export
 * @interface CreateDeepNewsResponseStreamSource
 */
export interface CreateDeepNewsResponseStreamSource {
    /**
     * 
     * @type {string}
     * @memberof CreateDeepNewsResponseStreamSource
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof CreateDeepNewsResponseStreamSource
     */
    created: number;
    /**
     * 
     * @type {string}
     * @memberof CreateDeepNewsResponseStreamSource
     */
    object?: string;
    /**
     * 
     * @type {Source}
     * @memberof CreateDeepNewsResponseStreamSource
     */
    source: Source;
}

/**
 * Check if a given object implements the CreateDeepNewsResponseStreamSource interface.
 */
export function instanceOfCreateDeepNewsResponseStreamSource(value: object): value is CreateDeepNewsResponseStreamSource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    return true;
}

export function CreateDeepNewsResponseStreamSourceFromJSON(json: any): CreateDeepNewsResponseStreamSource {
    return CreateDeepNewsResponseStreamSourceFromJSONTyped(json, false);
}

export function CreateDeepNewsResponseStreamSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDeepNewsResponseStreamSource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'created': json['created'],
        'object': json['object'] == null ? undefined : json['object'],
        'source': SourceFromJSON(json['source']),
    };
}

export function CreateDeepNewsResponseStreamSourceToJSON(json: any): CreateDeepNewsResponseStreamSource {
    return CreateDeepNewsResponseStreamSourceToJSONTyped(json, false);
}

export function CreateDeepNewsResponseStreamSourceToJSONTyped(value?: CreateDeepNewsResponseStreamSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'created': value['created'],
        'object': value['object'],
        'source': SourceToJSON(value['source']),
    };
}

