/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.66
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateDeepNewsResponseStreamChunkChoiceV2 } from './CreateDeepNewsResponseStreamChunkChoiceV2';
import {
    CreateDeepNewsResponseStreamChunkChoiceV2FromJSON,
    CreateDeepNewsResponseStreamChunkChoiceV2FromJSONTyped,
    CreateDeepNewsResponseStreamChunkChoiceV2ToJSON,
    CreateDeepNewsResponseStreamChunkChoiceV2ToJSONTyped,
} from './CreateDeepNewsResponseStreamChunkChoiceV2';
import type { CreateDeepNewsResponseUsage } from './CreateDeepNewsResponseUsage';
import {
    CreateDeepNewsResponseUsageFromJSON,
    CreateDeepNewsResponseUsageFromJSONTyped,
    CreateDeepNewsResponseUsageToJSON,
    CreateDeepNewsResponseUsageToJSONTyped,
} from './CreateDeepNewsResponseUsage';

/**
 * 
 * @export
 * @interface CreateDeepNewsResponseStreamChunkV2
 */
export interface CreateDeepNewsResponseStreamChunkV2 {
    /**
     * 
     * @type {string}
     * @memberof CreateDeepNewsResponseStreamChunkV2
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof CreateDeepNewsResponseStreamChunkV2
     */
    created: number;
    /**
     * 
     * @type {string}
     * @memberof CreateDeepNewsResponseStreamChunkV2
     */
    object?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDeepNewsResponseStreamChunkV2
     */
    model?: string;
    /**
     * 
     * @type {CreateDeepNewsResponseUsage}
     * @memberof CreateDeepNewsResponseStreamChunkV2
     */
    usage: CreateDeepNewsResponseUsage;
    /**
     * 
     * @type {Array<CreateDeepNewsResponseStreamChunkChoiceV2>}
     * @memberof CreateDeepNewsResponseStreamChunkV2
     */
    choices: Array<CreateDeepNewsResponseStreamChunkChoiceV2>;
}

/**
 * Check if a given object implements the CreateDeepNewsResponseStreamChunkV2 interface.
 */
export function instanceOfCreateDeepNewsResponseStreamChunkV2(value: object): value is CreateDeepNewsResponseStreamChunkV2 {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('usage' in value) || value['usage'] === undefined) return false;
    if (!('choices' in value) || value['choices'] === undefined) return false;
    return true;
}

export function CreateDeepNewsResponseStreamChunkV2FromJSON(json: any): CreateDeepNewsResponseStreamChunkV2 {
    return CreateDeepNewsResponseStreamChunkV2FromJSONTyped(json, false);
}

export function CreateDeepNewsResponseStreamChunkV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDeepNewsResponseStreamChunkV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'created': json['created'],
        'object': json['object'] == null ? undefined : json['object'],
        'model': json['model'] == null ? undefined : json['model'],
        'usage': CreateDeepNewsResponseUsageFromJSON(json['usage']),
        'choices': ((json['choices'] as Array<any>).map(CreateDeepNewsResponseStreamChunkChoiceV2FromJSON)),
    };
}

export function CreateDeepNewsResponseStreamChunkV2ToJSON(json: any): CreateDeepNewsResponseStreamChunkV2 {
    return CreateDeepNewsResponseStreamChunkV2ToJSONTyped(json, false);
}

export function CreateDeepNewsResponseStreamChunkV2ToJSONTyped(value?: CreateDeepNewsResponseStreamChunkV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'created': value['created'],
        'object': value['object'],
        'model': value['model'],
        'usage': CreateDeepNewsResponseUsageToJSON(value['usage']),
        'choices': ((value['choices'] as Array<any>).map(CreateDeepNewsResponseStreamChunkChoiceV2ToJSON)),
    };
}

