/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.66
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CreateDeepNewsResponseStreamChunk1 } from './CreateDeepNewsResponseStreamChunk1';
import {
    instanceOfCreateDeepNewsResponseStreamChunk1,
    CreateDeepNewsResponseStreamChunk1FromJSON,
    CreateDeepNewsResponseStreamChunk1FromJSONTyped,
    CreateDeepNewsResponseStreamChunk1ToJSON,
} from './CreateDeepNewsResponseStreamChunk1';
import type { CreateDeepNewsResponseStreamChunkV21 } from './CreateDeepNewsResponseStreamChunkV21';
import {
    instanceOfCreateDeepNewsResponseStreamChunkV21,
    CreateDeepNewsResponseStreamChunkV21FromJSON,
    CreateDeepNewsResponseStreamChunkV21FromJSONTyped,
    CreateDeepNewsResponseStreamChunkV21ToJSON,
} from './CreateDeepNewsResponseStreamChunkV21';
import type { CreateDeepNewsResponseStreamSource1 } from './CreateDeepNewsResponseStreamSource1';
import {
    instanceOfCreateDeepNewsResponseStreamSource1,
    CreateDeepNewsResponseStreamSource1FromJSON,
    CreateDeepNewsResponseStreamSource1FromJSONTyped,
    CreateDeepNewsResponseStreamSource1ToJSON,
} from './CreateDeepNewsResponseStreamSource1';

/**
 * @type DeepNews200Response
 * 
 * @export
 */
export type DeepNews200Response = CreateDeepNewsResponseStreamChunk1 | CreateDeepNewsResponseStreamChunkV21 | CreateDeepNewsResponseStreamSource1;

export function DeepNews200ResponseFromJSON(json: any): DeepNews200Response {
    return DeepNews200ResponseFromJSONTyped(json, false);
}

export function DeepNews200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeepNews200Response {
    if (json == null) {
        return json;
    }
    if (instanceOfCreateDeepNewsResponseStreamChunk1(json)) {
        return CreateDeepNewsResponseStreamChunk1FromJSONTyped(json, true);
    }
    if (instanceOfCreateDeepNewsResponseStreamChunkV21(json)) {
        return CreateDeepNewsResponseStreamChunkV21FromJSONTyped(json, true);
    }
    if (instanceOfCreateDeepNewsResponseStreamSource1(json)) {
        return CreateDeepNewsResponseStreamSource1FromJSONTyped(json, true);
    }

    return {} as any;
}

export function DeepNews200ResponseToJSON(json: any): any {
    return DeepNews200ResponseToJSONTyped(json, false);
}

export function DeepNews200ResponseToJSONTyped(value?: DeepNews200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfCreateDeepNewsResponseStreamChunk1(value)) {
        return CreateDeepNewsResponseStreamChunk1ToJSON(value as CreateDeepNewsResponseStreamChunk1);
    }
    if (instanceOfCreateDeepNewsResponseStreamChunkV21(value)) {
        return CreateDeepNewsResponseStreamChunkV21ToJSON(value as CreateDeepNewsResponseStreamChunkV21);
    }
    if (instanceOfCreateDeepNewsResponseStreamSource1(value)) {
        return CreateDeepNewsResponseStreamSource1ToJSON(value as CreateDeepNewsResponseStreamSource1);
    }

    return {};
}

