/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.54
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeepNewsReportParams } from './DeepNewsReportParams';
import {
    DeepNewsReportParamsFromJSON,
    DeepNewsReportParamsFromJSONTyped,
    DeepNewsReportParamsToJSON,
    DeepNewsReportParamsToJSONTyped,
} from './DeepNewsReportParams';

/**
 * DeepNews report configuration.
 * 
 * Uses DeepNews deep research capabilities for information retrieval and report generation.
 * @export
 * @interface DeepNewsReportRequest
 */
export interface DeepNewsReportRequest {
    /**
     * 
     * @type {string}
     * @memberof DeepNewsReportRequest
     */
    logoUrl?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DeepNewsReportRequest
     */
    includeAppendix?: boolean | null;
    /**
     * Append 'Generated by AskNews AI' watermark
     * @type {boolean}
     * @memberof DeepNewsReportRequest
     */
    asknewsWatermark?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DeepNewsReportRequest
     */
    identifier?: DeepNewsReportRequestIdentifierEnum;
    /**
     * 
     * @type {DeepNewsReportParams}
     * @memberof DeepNewsReportRequest
     */
    params?: DeepNewsReportParams;
    /**
     * The prompt to use for report generation instructions. This is similar to the alert query but can contain additional instructions on how to format the report.
     * @type {string}
     * @memberof DeepNewsReportRequest
     */
    prompt: string;
}


/**
 * @export
 */
export const DeepNewsReportRequestIdentifierEnum = {
    Deepnews: 'deepnews'
} as const;
export type DeepNewsReportRequestIdentifierEnum = typeof DeepNewsReportRequestIdentifierEnum[keyof typeof DeepNewsReportRequestIdentifierEnum];


/**
 * Check if a given object implements the DeepNewsReportRequest interface.
 */
export function instanceOfDeepNewsReportRequest(value: object): value is DeepNewsReportRequest {
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function DeepNewsReportRequestFromJSON(json: any): DeepNewsReportRequest {
    return DeepNewsReportRequestFromJSONTyped(json, false);
}

export function DeepNewsReportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeepNewsReportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'logoUrl': json['logo_url'] == null ? undefined : json['logo_url'],
        'includeAppendix': json['include_appendix'] == null ? undefined : json['include_appendix'],
        'asknewsWatermark': json['asknews_watermark'] == null ? undefined : json['asknews_watermark'],
        'identifier': json['identifier'] == null ? undefined : json['identifier'],
        'params': json['params'] == null ? undefined : DeepNewsReportParamsFromJSON(json['params']),
        'prompt': json['prompt'],
    };
}

export function DeepNewsReportRequestToJSON(json: any): DeepNewsReportRequest {
    return DeepNewsReportRequestToJSONTyped(json, false);
}

export function DeepNewsReportRequestToJSONTyped(value?: DeepNewsReportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'logo_url': value['logoUrl'],
        'include_appendix': value['includeAppendix'],
        'asknews_watermark': value['asknewsWatermark'],
        'identifier': value['identifier'],
        'params': DeepNewsReportParamsToJSON(value['params']),
        'prompt': value['prompt'],
    };
}

