/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.50
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FilterParams } from './FilterParams';
import {
    FilterParamsFromJSON,
    FilterParamsFromJSONTyped,
    FilterParamsToJSON,
    FilterParamsToJSONTyped,
} from './FilterParams';
import type { Sources2 } from './Sources2';
import {
    Sources2FromJSON,
    Sources2FromJSONTyped,
    Sources2ToJSON,
    Sources2ToJSONTyped,
} from './Sources2';
import type { DeepNewsModel } from './DeepNewsModel';
import {
    DeepNewsModelFromJSON,
    DeepNewsModelFromJSONTyped,
    DeepNewsModelToJSON,
    DeepNewsModelToJSONTyped,
} from './DeepNewsModel';

/**
 * Parameters for DeepNews alert source.
 * 
 * DeepNews performs deep research using multiple tools.
 * @export
 * @interface DeepNewsSourceParams
 */
export interface DeepNewsSourceParams {
    /**
     * 
     * @type {Sources2}
     * @memberof DeepNewsSourceParams
     */
    sources?: Sources2;
    /**
     * 
     * @type {FilterParams}
     * @memberof DeepNewsSourceParams
     */
    filterParams?: FilterParams | null;
    /**
     * Whether to provide extracted entities to the agent. Defaults to True.
     * @type {boolean}
     * @memberof DeepNewsSourceParams
     */
    includeEntities?: boolean;
    /**
     * Whether to provide knowledge graphs to the agent. Defaults to False.
     * @type {boolean}
     * @memberof DeepNewsSourceParams
     */
    includeGraphs?: boolean;
    /**
     * Whether to provide geo coordinates to the agent. Defaults to False.
     * @type {boolean}
     * @memberof DeepNewsSourceParams
     */
    includeCoordinates?: boolean;
    /**
     * 
     * @type {DeepNewsModel}
     * @memberof DeepNewsSourceParams
     */
    model?: DeepNewsModel | null;
    /**
     * The search depth for deep research. Higher values mean more thorough research. Defaults to 2.
     * @type {number}
     * @memberof DeepNewsSourceParams
     */
    searchDepth?: number;
    /**
     * The maximum research depth allowed. Defaults to 4.
     * @type {number}
     * @memberof DeepNewsSourceParams
     */
    maxDepth?: number;
}



/**
 * Check if a given object implements the DeepNewsSourceParams interface.
 */
export function instanceOfDeepNewsSourceParams(value: object): value is DeepNewsSourceParams {
    return true;
}

export function DeepNewsSourceParamsFromJSON(json: any): DeepNewsSourceParams {
    return DeepNewsSourceParamsFromJSONTyped(json, false);
}

export function DeepNewsSourceParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeepNewsSourceParams {
    if (json == null) {
        return json;
    }
    return {
        
        'sources': json['sources'] == null ? undefined : Sources2FromJSON(json['sources']),
        'filterParams': json['filter_params'] == null ? undefined : FilterParamsFromJSON(json['filter_params']),
        'includeEntities': json['include_entities'] == null ? undefined : json['include_entities'],
        'includeGraphs': json['include_graphs'] == null ? undefined : json['include_graphs'],
        'includeCoordinates': json['include_coordinates'] == null ? undefined : json['include_coordinates'],
        'model': json['model'] == null ? undefined : DeepNewsModelFromJSON(json['model']),
        'searchDepth': json['search_depth'] == null ? undefined : json['search_depth'],
        'maxDepth': json['max_depth'] == null ? undefined : json['max_depth'],
    };
}

export function DeepNewsSourceParamsToJSON(json: any): DeepNewsSourceParams {
    return DeepNewsSourceParamsToJSONTyped(json, false);
}

export function DeepNewsSourceParamsToJSONTyped(value?: DeepNewsSourceParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sources': Sources2ToJSON(value['sources']),
        'filter_params': FilterParamsToJSON(value['filterParams']),
        'include_entities': value['includeEntities'],
        'include_graphs': value['includeGraphs'],
        'include_coordinates': value['includeCoordinates'],
        'model': DeepNewsModelToJSON(value['model']),
        'search_depth': value['searchDepth'],
        'max_depth': value['maxDepth'],
    };
}

