/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainMetricsDayItem
 */
export interface DomainMetricsDayItem {
    /**
     * 
     * @type {string}
     * @memberof DomainMetricsDayItem
     */
    day: string;
    /**
     * 
     * @type {number}
     * @memberof DomainMetricsDayItem
     */
    surfaces: number;
    /**
     * 
     * @type {number}
     * @memberof DomainMetricsDayItem
     */
    citations: number;
    /**
     * 
     * @type {number}
     * @memberof DomainMetricsDayItem
     */
    fullText: number;
    /**
     * 
     * @type {number}
     * @memberof DomainMetricsDayItem
     */
    grounded?: number;
}

/**
 * Check if a given object implements the DomainMetricsDayItem interface.
 */
export function instanceOfDomainMetricsDayItem(value: object): value is DomainMetricsDayItem {
    if (!('day' in value) || value['day'] === undefined) return false;
    if (!('surfaces' in value) || value['surfaces'] === undefined) return false;
    if (!('citations' in value) || value['citations'] === undefined) return false;
    if (!('fullText' in value) || value['fullText'] === undefined) return false;
    return true;
}

export function DomainMetricsDayItemFromJSON(json: any): DomainMetricsDayItem {
    return DomainMetricsDayItemFromJSONTyped(json, false);
}

export function DomainMetricsDayItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainMetricsDayItem {
    if (json == null) {
        return json;
    }
    return {
        
        'day': json['day'],
        'surfaces': json['surfaces'],
        'citations': json['citations'],
        'fullText': json['full_text'],
        'grounded': json['grounded'] == null ? undefined : json['grounded'],
    };
}

export function DomainMetricsDayItemToJSON(json: any): DomainMetricsDayItem {
    return DomainMetricsDayItemToJSONTyped(json, false);
}

export function DomainMetricsDayItemToJSONTyped(value?: DomainMetricsDayItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'day': value['day'],
        'surfaces': value['surfaces'],
        'citations': value['citations'],
        'full_text': value['fullText'],
        'grounded': value['grounded'],
    };
}

