/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.8.6
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * End timestamp to filter by
 * @export
 * @interface EndTimestamp1
 */
export interface EndTimestamp1 {
}

/**
 * Check if a given object implements the EndTimestamp1 interface.
 */
export function instanceOfEndTimestamp1(value: object): boolean {
    return true;
}

export function EndTimestamp1FromJSON(json: any): EndTimestamp1 {
    return EndTimestamp1FromJSONTyped(json, false);
}

export function EndTimestamp1FromJSONTyped(json: any, ignoreDiscriminator: boolean): EndTimestamp1 {
    return json;
}

export function EndTimestamp1ToJSON(value?: EndTimestamp1 | null): any {
    return value;
}

