/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.20.5
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FilterParams1
 */
export interface FilterParams1 {
}

/**
 * Check if a given object implements the FilterParams1 interface.
 */
export function instanceOfFilterParams1(value: object): value is FilterParams1 {
    return true;
}

export function FilterParams1FromJSON(json: any): FilterParams1 {
    return FilterParams1FromJSONTyped(json, false);
}

export function FilterParams1FromJSONTyped(json: any, ignoreDiscriminator: boolean): FilterParams1 {
    return json;
}

export function FilterParams1ToJSON(json: any): FilterParams1 {
    return FilterParams1ToJSONTyped(json, false);
}

export function FilterParams1ToJSONTyped(value?: FilterParams1 | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

