/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.22.7
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FilterParams } from './FilterParams';
import {
    FilterParamsFromJSON,
    FilterParamsFromJSONTyped,
    FilterParamsToJSON,
    FilterParamsToJSONTyped,
} from './FilterParams';
import type { FilterParamsMetadata } from './FilterParamsMetadata';
import {
    FilterParamsMetadataFromJSON,
    FilterParamsMetadataFromJSONTyped,
    FilterParamsMetadataToJSON,
    FilterParamsMetadataToJSONTyped,
} from './FilterParamsMetadata';

/**
 * 
 * @export
 * @interface FilterParamsResponse
 */
export interface FilterParamsResponse {
    /**
     * 
     * @type {FilterParams}
     * @memberof FilterParamsResponse
     */
    filterParams: FilterParams;
    /**
     * 
     * @type {FilterParamsMetadata}
     * @memberof FilterParamsResponse
     */
    metadata: FilterParamsMetadata;
}

/**
 * Check if a given object implements the FilterParamsResponse interface.
 */
export function instanceOfFilterParamsResponse(value: object): value is FilterParamsResponse {
    if (!('filterParams' in value) || value['filterParams'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function FilterParamsResponseFromJSON(json: any): FilterParamsResponse {
    return FilterParamsResponseFromJSONTyped(json, false);
}

export function FilterParamsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilterParamsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'filterParams': FilterParamsFromJSON(json['filter_params']),
        'metadata': FilterParamsMetadataFromJSON(json['metadata']),
    };
}

export function FilterParamsResponseToJSON(json: any): FilterParamsResponse {
    return FilterParamsResponseToJSONTyped(json, false);
}

export function FilterParamsResponseToJSONTyped(value?: FilterParamsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filter_params': FilterParamsToJSON(value['filterParams']),
        'metadata': FilterParamsMetadataToJSON(value['metadata']),
    };
}

