/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.22
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FilterParams
 */
export interface FilterParams {
}

/**
 * Check if a given object implements the FilterParams interface.
 */
export function instanceOfFilterParams(value: object): value is FilterParams {
    return true;
}

export function FilterParamsFromJSON(json: any): FilterParams {
    return FilterParamsFromJSONTyped(json, false);
}

export function FilterParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilterParams {
    return json;
}

export function FilterParamsToJSON(json: any): FilterParams {
    return FilterParamsToJSONTyped(json, false);
}

export function FilterParamsToJSONTyped(value?: FilterParams | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

