/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.21.1
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoogleDocsParams
 */
export interface GoogleDocsParams {
    /**
     * The google service account json. This should be a dict. You can get this from the google cloud console. The document will be created in the service account's google drive and shared with the user.
     * @type {{ [key: string]: any; }}
     * @memberof GoogleDocsParams
     */
    clientJson: { [key: string]: any; };
    /**
     * 
     * @type {Array<string>}
     * @memberof GoogleDocsParams
     */
    emails?: Array<string> | null;
}

/**
 * Check if a given object implements the GoogleDocsParams interface.
 */
export function instanceOfGoogleDocsParams(value: object): value is GoogleDocsParams {
    if (!('clientJson' in value) || value['clientJson'] === undefined) return false;
    return true;
}

export function GoogleDocsParamsFromJSON(json: any): GoogleDocsParams {
    return GoogleDocsParamsFromJSONTyped(json, false);
}

export function GoogleDocsParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoogleDocsParams {
    if (json == null) {
        return json;
    }
    return {
        
        'clientJson': json['client_json'],
        'emails': json['emails'] == null ? undefined : json['emails'],
    };
}

export function GoogleDocsParamsToJSON(json: any): GoogleDocsParams {
    return GoogleDocsParamsToJSONTyped(json, false);
}

export function GoogleDocsParamsToJSONTyped(value?: GoogleDocsParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_json': value['clientJson'],
        'emails': value['emails'],
    };
}

