/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.24.4
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HitShareItem } from './HitShareItem';
import {
    HitShareItemFromJSON,
    HitShareItemFromJSONTyped,
    HitShareItemToJSON,
    HitShareItemToJSONTyped,
} from './HitShareItem';

/**
 * 
 * @export
 * @interface HitShareResponse
 */
export interface HitShareResponse {
    /**
     * 
     * @type {Array<HitShareItem>}
     * @memberof HitShareResponse
     */
    data: Array<HitShareItem>;
    /**
     * 
     * @type {number}
     * @memberof HitShareResponse
     */
    totalShare: number;
}

/**
 * Check if a given object implements the HitShareResponse interface.
 */
export function instanceOfHitShareResponse(value: object): value is HitShareResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('totalShare' in value) || value['totalShare'] === undefined) return false;
    return true;
}

export function HitShareResponseFromJSON(json: any): HitShareResponse {
    return HitShareResponseFromJSONTyped(json, false);
}

export function HitShareResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HitShareResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(HitShareItemFromJSON)),
        'totalShare': json['total_share'],
    };
}

export function HitShareResponseToJSON(json: any): HitShareResponse {
    return HitShareResponseToJSONTyped(json, false);
}

export function HitShareResponseToJSONTyped(value?: HitShareResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(HitShareItemToJSON)),
        'total_share': value['totalShare'],
    };
}

