/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.21.1
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KeyPerson
 */
export interface KeyPerson {
    /**
     * 
     * @type {string}
     * @memberof KeyPerson
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof KeyPerson
     */
    role: string;
}

/**
 * Check if a given object implements the KeyPerson interface.
 */
export function instanceOfKeyPerson(value: object): value is KeyPerson {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function KeyPersonFromJSON(json: any): KeyPerson {
    return KeyPersonFromJSONTyped(json, false);
}

export function KeyPersonFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeyPerson {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'role': json['role'],
    };
}

export function KeyPersonToJSON(json: any): KeyPerson {
    return KeyPersonToJSONTyped(json, false);
}

export function KeyPersonToJSONTyped(value?: KeyPerson | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'role': value['role'],
    };
}

