/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.50
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Legacy report configuration (original format).
 * 
 * This is the original ReportRequest format that uses a simple model field
 * for report generation without DeepNews capabilities.
 * @export
 * @interface LegacyReportRequest
 */
export interface LegacyReportRequest {
    /**
     * 
     * @type {Array<Array<string>>}
     * @memberof LegacyReportRequest
     */
    prompt?: Array<Array<string>> | null;
    /**
     * 
     * @type {string}
     * @memberof LegacyReportRequest
     */
    logoUrl?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof LegacyReportRequest
     */
    includeAppendix?: boolean | null;
    /**
     * Append 'Generated by AskNews AI' watermark
     * @type {boolean}
     * @memberof LegacyReportRequest
     */
    asknewsWatermark?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LegacyReportRequest
     */
    identifier?: LegacyReportRequestIdentifierEnum;
    /**
     * The model to use for the report. Defaults to claude-sonnet-4-5-20250929.
     * @type {string}
     * @memberof LegacyReportRequest
     */
    model?: LegacyReportRequestModelEnum;
}


/**
 * @export
 */
export const LegacyReportRequestIdentifierEnum = {
    Legacy: 'legacy'
} as const;
export type LegacyReportRequestIdentifierEnum = typeof LegacyReportRequestIdentifierEnum[keyof typeof LegacyReportRequestIdentifierEnum];

/**
 * @export
 */
export const LegacyReportRequestModelEnum = {
    Gpt5: 'gpt-5',
    Gpt4o: 'gpt-4o',
    Gpt4120250414: 'gpt-4.1-2025-04-14',
    Gpt41Mini20250414: 'gpt-4.1-mini-2025-04-14',
    Gpt4oMini: 'gpt-4o-mini',
    O3Mini: 'o3-mini',
    Claude35SonnetLatest: 'claude-3-5-sonnet-latest',
    ClaudeSonnet420250514: 'claude-sonnet-4-20250514',
    ClaudeSonnet4520250929: 'claude-sonnet-4-5-20250929',
    ClaudeOpus4520251101: 'claude-opus-4-5-20251101',
    ClaudeOpus46: 'claude-opus-4-6',
    ClaudeSonnet46: 'claude-sonnet-4-6',
    MetaLlamaMetaLlama31405BInstruct: 'meta-llama/Meta-Llama-3.1-405B-Instruct',
    MetaLlamaMetaLlama3370BInstruct: 'meta-llama/Meta-Llama-3.3-70B-Instruct'
} as const;
export type LegacyReportRequestModelEnum = typeof LegacyReportRequestModelEnum[keyof typeof LegacyReportRequestModelEnum];


/**
 * Check if a given object implements the LegacyReportRequest interface.
 */
export function instanceOfLegacyReportRequest(value: object): value is LegacyReportRequest {
    return true;
}

export function LegacyReportRequestFromJSON(json: any): LegacyReportRequest {
    return LegacyReportRequestFromJSONTyped(json, false);
}

export function LegacyReportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegacyReportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt': json['prompt'] == null ? undefined : json['prompt'],
        'logoUrl': json['logo_url'] == null ? undefined : json['logo_url'],
        'includeAppendix': json['include_appendix'] == null ? undefined : json['include_appendix'],
        'asknewsWatermark': json['asknews_watermark'] == null ? undefined : json['asknews_watermark'],
        'identifier': json['identifier'] == null ? undefined : json['identifier'],
        'model': json['model'] == null ? undefined : json['model'],
    };
}

export function LegacyReportRequestToJSON(json: any): LegacyReportRequest {
    return LegacyReportRequestToJSONTyped(json, false);
}

export function LegacyReportRequestToJSONTyped(value?: LegacyReportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt': value['prompt'],
        'logo_url': value['logoUrl'],
        'include_appendix': value['includeAppendix'],
        'asknews_watermark': value['asknewsWatermark'],
        'identifier': value['identifier'],
        'model': value['model'],
    };
}

