/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.43
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelItem } from './ModelItem';
import {
    ModelItemFromJSON,
    ModelItemFromJSONTyped,
    ModelItemToJSON,
    ModelItemToJSONTyped,
} from './ModelItem';

/**
 * 
 * @export
 * @interface ListModelResponse
 */
export interface ListModelResponse {
    /**
     * 
     * @type {string}
     * @memberof ListModelResponse
     */
    object?: string;
    /**
     * 
     * @type {Array<ModelItem>}
     * @memberof ListModelResponse
     */
    data: Array<ModelItem>;
}

/**
 * Check if a given object implements the ListModelResponse interface.
 */
export function instanceOfListModelResponse(value: object): value is ListModelResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListModelResponseFromJSON(json: any): ListModelResponse {
    return ListModelResponseFromJSONTyped(json, false);
}

export function ListModelResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListModelResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'] == null ? undefined : json['object'],
        'data': ((json['data'] as Array<any>).map(ModelItemFromJSON)),
    };
}

export function ListModelResponseToJSON(json: any): ListModelResponse {
    return ListModelResponseToJSONTyped(json, false);
}

export function ListModelResponseToJSONTyped(value?: ListModelResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'object': value['object'],
        'data': ((value['data'] as Array<any>).map(ModelItemToJSON)),
    };
}

