/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageStopEvent
 */
export interface MessageStopEvent {
    /**
     * 
     * @type {string}
     * @memberof MessageStopEvent
     */
    type?: MessageStopEventTypeEnum;
}


/**
 * @export
 */
export const MessageStopEventTypeEnum = {
    MessageStop: 'message_stop'
} as const;
export type MessageStopEventTypeEnum = typeof MessageStopEventTypeEnum[keyof typeof MessageStopEventTypeEnum];


/**
 * Check if a given object implements the MessageStopEvent interface.
 */
export function instanceOfMessageStopEvent(value: object): value is MessageStopEvent {
    return true;
}

export function MessageStopEventFromJSON(json: any): MessageStopEvent {
    return MessageStopEventFromJSONTyped(json, false);
}

export function MessageStopEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageStopEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function MessageStopEventToJSON(json: any): MessageStopEvent {
    return MessageStopEventToJSONTyped(json, false);
}

export function MessageStopEventToJSONTyped(value?: MessageStopEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

