/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageStartEvent1
 */
export interface MessageStartEvent1 {
    /**
     * 
     * @type {string}
     * @memberof MessageStartEvent1
     */
    type?: MessageStartEvent1TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof MessageStartEvent1
     */
    role?: MessageStartEvent1RoleEnum;
}


/**
 * @export
 */
export const MessageStartEvent1TypeEnum = {
    MessageStart: 'message_start'
} as const;
export type MessageStartEvent1TypeEnum = typeof MessageStartEvent1TypeEnum[keyof typeof MessageStartEvent1TypeEnum];

/**
 * @export
 */
export const MessageStartEvent1RoleEnum = {
    Assistant: 'assistant'
} as const;
export type MessageStartEvent1RoleEnum = typeof MessageStartEvent1RoleEnum[keyof typeof MessageStartEvent1RoleEnum];


/**
 * Check if a given object implements the MessageStartEvent1 interface.
 */
export function instanceOfMessageStartEvent1(value: object): value is MessageStartEvent1 {
    return true;
}

export function MessageStartEvent1FromJSON(json: any): MessageStartEvent1 {
    return MessageStartEvent1FromJSONTyped(json, false);
}

export function MessageStartEvent1FromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageStartEvent1 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function MessageStartEvent1ToJSON(json: any): MessageStartEvent1 {
    return MessageStartEvent1ToJSONTyped(json, false);
}

export function MessageStartEvent1ToJSONTyped(value?: MessageStartEvent1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'role': value['role'],
    };
}

