/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.28
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelItem
 */
export interface ModelItem {
    /**
     * 
     * @type {string}
     * @memberof ModelItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ModelItem
     */
    object?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelItem
     */
    created?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelItem
     */
    ownedBy?: string;
}

/**
 * Check if a given object implements the ModelItem interface.
 */
export function instanceOfModelItem(value: object): value is ModelItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ModelItemFromJSON(json: any): ModelItem {
    return ModelItemFromJSONTyped(json, false);
}

export function ModelItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'object': json['object'] == null ? undefined : json['object'],
        'created': json['created'] == null ? undefined : json['created'],
        'ownedBy': json['owned_by'] == null ? undefined : json['owned_by'],
    };
}

export function ModelItemToJSON(json: any): ModelItem {
    return ModelItemToJSONTyped(json, false);
}

export function ModelItemToJSONTyped(value?: ModelItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object': value['object'],
        'created': value['created'],
        'owned_by': value['ownedBy'],
    };
}

