/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.18.19
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewsletterContactCreateResponse
 */
export interface NewsletterContactCreateResponse {
    /**
     * 
     * @type {string}
     * @memberof NewsletterContactCreateResponse
     */
    id: string;
}

/**
 * Check if a given object implements the NewsletterContactCreateResponse interface.
 */
export function instanceOfNewsletterContactCreateResponse(value: object): boolean {
    if (!('id' in value)) return false;
    return true;
}

export function NewsletterContactCreateResponseFromJSON(json: any): NewsletterContactCreateResponse {
    return NewsletterContactCreateResponseFromJSONTyped(json, false);
}

export function NewsletterContactCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewsletterContactCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function NewsletterContactCreateResponseToJSON(value?: NewsletterContactCreateResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

