/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.45
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewsletterContactRequest
 */
export interface NewsletterContactRequest {
    /**
     * 
     * @type {string}
     * @memberof NewsletterContactRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof NewsletterContactRequest
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NewsletterContactRequest
     */
    lastName?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof NewsletterContactRequest
     */
    unsubscribed?: boolean;
}

/**
 * Check if a given object implements the NewsletterContactRequest interface.
 */
export function instanceOfNewsletterContactRequest(value: object): value is NewsletterContactRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function NewsletterContactRequestFromJSON(json: any): NewsletterContactRequest {
    return NewsletterContactRequestFromJSONTyped(json, false);
}

export function NewsletterContactRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewsletterContactRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'unsubscribed': json['unsubscribed'] == null ? undefined : json['unsubscribed'],
    };
}

export function NewsletterContactRequestToJSON(json: any): NewsletterContactRequest {
    return NewsletterContactRequestToJSONTyped(json, false);
}

export function NewsletterContactRequestToJSONTyped(value?: NewsletterContactRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'unsubscribed': value['unsubscribed'],
    };
}

