/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Offset6
 */
export interface Offset6 {
}

/**
 * Check if a given object implements the Offset6 interface.
 */
export function instanceOfOffset6(value: object): value is Offset6 {
    return true;
}

export function Offset6FromJSON(json: any): Offset6 {
    return Offset6FromJSONTyped(json, false);
}

export function Offset6FromJSONTyped(json: any, ignoreDiscriminator: boolean): Offset6 {
    return json;
}

export function Offset6ToJSON(json: any): Offset6 {
    return Offset6ToJSONTyped(json, false);
}

export function Offset6ToJSONTyped(value?: Offset6 | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

