/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.16.0
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Offset3
 */
export interface Offset3 {
}

/**
 * Check if a given object implements the Offset3 interface.
 */
export function instanceOfOffset3(value: object): boolean {
    return true;
}

export function Offset3FromJSON(json: any): Offset3 {
    return Offset3FromJSONTyped(json, false);
}

export function Offset3FromJSONTyped(json: any, ignoreDiscriminator: boolean): Offset3 {
    return json;
}

export function Offset3ToJSON(value?: Offset3 | null): any {
    return value;
}

