/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.23.2
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Offset4
 */
export interface Offset4 {
}

/**
 * Check if a given object implements the Offset4 interface.
 */
export function instanceOfOffset4(value: object): value is Offset4 {
    return true;
}

export function Offset4FromJSON(json: any): Offset4 {
    return Offset4FromJSONTyped(json, false);
}

export function Offset4FromJSONTyped(json: any, ignoreDiscriminator: boolean): Offset4 {
    return json;
}

export function Offset4ToJSON(json: any): Offset4 {
    return Offset4ToJSONTyped(json, false);
}

export function Offset4ToJSONTyped(value?: Offset4 | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

