/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.15.0
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Offset2
 */
export interface Offset2 {
}

/**
 * Check if a given object implements the Offset2 interface.
 */
export function instanceOfOffset2(value: object): boolean {
    return true;
}

export function Offset2FromJSON(json: any): Offset2 {
    return Offset2FromJSONTyped(json, false);
}

export function Offset2FromJSONTyped(json: any, ignoreDiscriminator: boolean): Offset2 {
    return json;
}

export function Offset2ToJSON(value?: Offset2 | null): any {
    return value;
}

