/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.18.22
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Offset for pagination. The n_articles is your page size, while your offset is the number of articles to skip to get to your page of interest. For example, if you want to get page 3 for n_article page size of 10, you would set offset to 20.
 * @export
 * @interface Offset2
 */
export interface Offset2 {
}

/**
 * Check if a given object implements the Offset2 interface.
 */
export function instanceOfOffset2(value: object): value is Offset2 {
    return true;
}

export function Offset2FromJSON(json: any): Offset2 {
    return Offset2FromJSONTyped(json, false);
}

export function Offset2FromJSONTyped(json: any, ignoreDiscriminator: boolean): Offset2 {
    return json;
}

export function Offset2ToJSON(json: any): Offset2 {
    return Offset2ToJSONTyped(json, false);
}

export function Offset2ToJSONTyped(value?: Offset2 | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

