/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.23.2
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReadDomainResponse
 */
export interface ReadDomainResponse {
    /**
     * 
     * @type {string}
     * @memberof ReadDomainResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ReadDomainResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ReadDomainResponse
     */
    owner?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ReadDomainResponse
     */
    isTollbit?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ReadDomainResponse
     */
    publisher?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ReadDomainResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ReadDomainResponse
     */
    updatedAt?: Date | null;
}

/**
 * Check if a given object implements the ReadDomainResponse interface.
 */
export function instanceOfReadDomainResponse(value: object): value is ReadDomainResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ReadDomainResponseFromJSON(json: any): ReadDomainResponse {
    return ReadDomainResponseFromJSONTyped(json, false);
}

export function ReadDomainResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadDomainResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'owner': json['owner'] == null ? undefined : json['owner'],
        'isTollbit': json['is_tollbit'] == null ? undefined : json['is_tollbit'],
        'publisher': json['publisher'] == null ? undefined : json['publisher'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function ReadDomainResponseToJSON(json: any): ReadDomainResponse {
    return ReadDomainResponseToJSONTyped(json, false);
}

export function ReadDomainResponseToJSONTyped(value?: ReadDomainResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'owner': value['owner'],
        'is_tollbit': value['isTollbit'],
        'publisher': value['publisher'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': value['updatedAt'] == null ? undefined : ((value['updatedAt'] as any).toISOString()),
    };
}

