/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.54
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeepNewsReportParams } from './DeepNewsReportParams';
import {
    DeepNewsReportParamsFromJSON,
    DeepNewsReportParamsFromJSONTyped,
    DeepNewsReportParamsToJSON,
    DeepNewsReportParamsToJSONTyped,
} from './DeepNewsReportParams';
import type { DeepNewsReportRequest } from './DeepNewsReportRequest';
import {
    DeepNewsReportRequestFromJSON,
    DeepNewsReportRequestFromJSONTyped,
    DeepNewsReportRequestToJSON,
    DeepNewsReportRequestToJSONTyped,
} from './DeepNewsReportRequest';
import type { LegacyReportRequest } from './LegacyReportRequest';
import {
    LegacyReportRequestFromJSON,
    LegacyReportRequestFromJSONTyped,
    LegacyReportRequestToJSON,
    LegacyReportRequestToJSONTyped,
} from './LegacyReportRequest';

/**
 * 
 * @export
 * @interface Report2AnyOfInner
 */
export interface Report2AnyOfInner {
    /**
     * 
     * @type {string}
     * @memberof Report2AnyOfInner
     */
    logoUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Report2AnyOfInner
     */
    includeAppendix?: boolean;
    /**
     * Append 'Generated by AskNews AI' watermark
     * @type {boolean}
     * @memberof Report2AnyOfInner
     */
    asknewsWatermark?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Report2AnyOfInner
     */
    identifier?: Report2AnyOfInnerIdentifierEnum;
    /**
     * The model to use for the report. Defaults to claude-sonnet-4-6.
     * @type {string}
     * @memberof Report2AnyOfInner
     */
    model?: Report2AnyOfInnerModelEnum;
    /**
     * 
     * @type {DeepNewsReportParams}
     * @memberof Report2AnyOfInner
     */
    params?: DeepNewsReportParams;
    /**
     * The prompt to use for report generation instructions. This is similar to the alert query but can contain additional instructions on how to format the report.
     * @type {string}
     * @memberof Report2AnyOfInner
     */
    prompt: string;
}


/**
 * @export
 */
export const Report2AnyOfInnerIdentifierEnum = {
    Deepnews: 'deepnews'
} as const;
export type Report2AnyOfInnerIdentifierEnum = typeof Report2AnyOfInnerIdentifierEnum[keyof typeof Report2AnyOfInnerIdentifierEnum];

/**
 * @export
 */
export const Report2AnyOfInnerModelEnum = {
    Gpt5: 'gpt-5',
    Gpt4o: 'gpt-4o',
    Gpt4120250414: 'gpt-4.1-2025-04-14',
    Gpt41Mini20250414: 'gpt-4.1-mini-2025-04-14',
    Gpt4oMini: 'gpt-4o-mini',
    O3Mini: 'o3-mini',
    Claude35SonnetLatest: 'claude-3-5-sonnet-latest',
    ClaudeSonnet420250514: 'claude-sonnet-4-20250514',
    ClaudeSonnet4520250929: 'claude-sonnet-4-5-20250929',
    ClaudeOpus4520251101: 'claude-opus-4-5-20251101',
    ClaudeOpus46: 'claude-opus-4-6',
    ClaudeSonnet46: 'claude-sonnet-4-6',
    MetaLlamaMetaLlama31405BInstruct: 'meta-llama/Meta-Llama-3.1-405B-Instruct',
    MetaLlamaMetaLlama3370BInstruct: 'meta-llama/Meta-Llama-3.3-70B-Instruct'
} as const;
export type Report2AnyOfInnerModelEnum = typeof Report2AnyOfInnerModelEnum[keyof typeof Report2AnyOfInnerModelEnum];


/**
 * Check if a given object implements the Report2AnyOfInner interface.
 */
export function instanceOfReport2AnyOfInner(value: object): value is Report2AnyOfInner {
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function Report2AnyOfInnerFromJSON(json: any): Report2AnyOfInner {
    return Report2AnyOfInnerFromJSONTyped(json, false);
}

export function Report2AnyOfInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Report2AnyOfInner {
    if (json == null) {
        return json;
    }
    return {
        
        'logoUrl': json['logo_url'] == null ? undefined : json['logo_url'],
        'includeAppendix': json['include_appendix'] == null ? undefined : json['include_appendix'],
        'asknewsWatermark': json['asknews_watermark'] == null ? undefined : json['asknews_watermark'],
        'identifier': json['identifier'] == null ? undefined : json['identifier'],
        'model': json['model'] == null ? undefined : json['model'],
        'params': json['params'] == null ? undefined : DeepNewsReportParamsFromJSON(json['params']),
        'prompt': json['prompt'],
    };
}

export function Report2AnyOfInnerToJSON(json: any): Report2AnyOfInner {
    return Report2AnyOfInnerToJSONTyped(json, false);
}

export function Report2AnyOfInnerToJSONTyped(value?: Report2AnyOfInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'logo_url': value['logoUrl'],
        'include_appendix': value['includeAppendix'],
        'asknews_watermark': value['asknewsWatermark'],
        'identifier': value['identifier'],
        'model': value['model'],
        'params': DeepNewsReportParamsToJSON(value['params']),
        'prompt': value['prompt'],
    };
}

