/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.23.2
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReportingVoice1
 */
export interface ReportingVoice1 {
}

/**
 * Check if a given object implements the ReportingVoice1 interface.
 */
export function instanceOfReportingVoice1(value: object): value is ReportingVoice1 {
    return true;
}

export function ReportingVoice1FromJSON(json: any): ReportingVoice1 {
    return ReportingVoice1FromJSONTyped(json, false);
}

export function ReportingVoice1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportingVoice1 {
    return json;
}

export function ReportingVoice1ToJSON(json: any): ReportingVoice1 {
    return ReportingVoice1ToJSONTyped(json, false);
}

export function ReportingVoice1ToJSONTyped(value?: ReportingVoice1 | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

