/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.28
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Type of reporting voice to filer by.
 * @export
 * @interface ReportingVoice2
 */
export interface ReportingVoice2 {
}

/**
 * Check if a given object implements the ReportingVoice2 interface.
 */
export function instanceOfReportingVoice2(value: object): value is ReportingVoice2 {
    return true;
}

export function ReportingVoice2FromJSON(json: any): ReportingVoice2 {
    return ReportingVoice2FromJSONTyped(json, false);
}

export function ReportingVoice2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportingVoice2 {
    return json;
}

export function ReportingVoice2ToJSON(json: any): ReportingVoice2 {
    return ReportingVoice2ToJSONTyped(json, false);
}

export function ReportingVoice2ToJSONTyped(value?: ReportingVoice2 | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

