/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Usage } from './Usage';
import {
    UsageFromJSON,
    UsageFromJSONTyped,
    UsageToJSON,
    UsageToJSONTyped,
} from './Usage';
import type { Offset5 } from './Offset5';
import {
    Offset5FromJSON,
    Offset5FromJSONTyped,
    Offset5ToJSON,
    Offset5ToJSONTyped,
} from './Offset5';
import type { SearchResponseDictItem } from './SearchResponseDictItem';
import {
    SearchResponseDictItemFromJSON,
    SearchResponseDictItemFromJSONTyped,
    SearchResponseDictItemToJSON,
    SearchResponseDictItemToJSONTyped,
} from './SearchResponseDictItem';

/**
 * 
 * @export
 * @interface SearchResponse
 */
export interface SearchResponse {
    /**
     * 
     * @type {Array<SearchResponseDictItem>}
     * @memberof SearchResponse
     */
    asDicts?: Array<SearchResponseDictItem> | null;
    /**
     * 
     * @type {string}
     * @memberof SearchResponse
     */
    asString?: string | null;
    /**
     * 
     * @type {Offset5}
     * @memberof SearchResponse
     */
    offset?: Offset5 | null;
    /**
     * 
     * @type {Usage}
     * @memberof SearchResponse
     */
    usage?: Usage | null;
}

/**
 * Check if a given object implements the SearchResponse interface.
 */
export function instanceOfSearchResponse(value: object): value is SearchResponse {
    return true;
}

export function SearchResponseFromJSON(json: any): SearchResponse {
    return SearchResponseFromJSONTyped(json, false);
}

export function SearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'asDicts': json['as_dicts'] == null ? undefined : ((json['as_dicts'] as Array<any>).map(SearchResponseDictItemFromJSON)),
        'asString': json['as_string'] == null ? undefined : json['as_string'],
        'offset': json['offset'] == null ? undefined : Offset5FromJSON(json['offset']),
        'usage': json['usage'] == null ? undefined : UsageFromJSON(json['usage']),
    };
}

export function SearchResponseToJSON(json: any): SearchResponse {
    return SearchResponseToJSONTyped(json, false);
}

export function SearchResponseToJSONTyped(value?: SearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'as_dicts': value['asDicts'] == null ? undefined : ((value['asDicts'] as Array<any>).map(SearchResponseDictItemToJSON)),
        'as_string': value['asString'],
        'offset': Offset5ToJSON(value['offset']),
        'usage': UsageToJSON(value['usage']),
    };
}

