/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.8.6
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AsDicts1 } from './AsDicts1';
import {
    AsDicts1FromJSON,
    AsDicts1FromJSONTyped,
    AsDicts1ToJSON,
} from './AsDicts1';
import type { AsString } from './AsString';
import {
    AsStringFromJSON,
    AsStringFromJSONTyped,
    AsStringToJSON,
} from './AsString';
import type { Offset } from './Offset';
import {
    OffsetFromJSON,
    OffsetFromJSONTyped,
    OffsetToJSON,
} from './Offset';

/**
 * 
 * @export
 * @interface SearchResponse
 */
export interface SearchResponse {
    /**
     * 
     * @type {AsDicts1}
     * @memberof SearchResponse
     */
    asDicts?: AsDicts1;
    /**
     * 
     * @type {AsString}
     * @memberof SearchResponse
     */
    asString?: AsString;
    /**
     * 
     * @type {Offset}
     * @memberof SearchResponse
     */
    offset?: Offset;
}

/**
 * Check if a given object implements the SearchResponse interface.
 */
export function instanceOfSearchResponse(value: object): boolean {
    return true;
}

export function SearchResponseFromJSON(json: any): SearchResponse {
    return SearchResponseFromJSONTyped(json, false);
}

export function SearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'asDicts': json['as_dicts'] == null ? undefined : AsDicts1FromJSON(json['as_dicts']),
        'asString': json['as_string'] == null ? undefined : AsStringFromJSON(json['as_string']),
        'offset': json['offset'] == null ? undefined : OffsetFromJSON(json['offset']),
    };
}

export function SearchResponseToJSON(value?: SearchResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'as_dicts': AsDicts1ToJSON(value['asDicts']),
        'as_string': AsStringToJSON(value['asString']),
        'offset': OffsetToJSON(value['offset']),
    };
}

