/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.43
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Which data sources DeepNews should use. Can be a single source or a list. Available sources are: asknews, google, graph, wiki, x, reddit, charts
 * @export
 * @interface Sources2
 */
export interface Sources2 {
}

/**
 * Check if a given object implements the Sources2 interface.
 */
export function instanceOfSources2(value: object): value is Sources2 {
    return true;
}

export function Sources2FromJSON(json: any): Sources2 {
    return Sources2FromJSONTyped(json, false);
}

export function Sources2FromJSONTyped(json: any, ignoreDiscriminator: boolean): Sources2 {
    return json;
}

export function Sources2ToJSON(json: any): Sources2 {
    return Sources2ToJSONTyped(json, false);
}

export function Sources2ToJSONTyped(value?: Sources2 | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

