/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.45
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateDeepNewsResponseStreamSourcesGraphSource } from './CreateDeepNewsResponseStreamSourcesGraphSource';
import {
    CreateDeepNewsResponseStreamSourcesGraphSourceFromJSON,
    CreateDeepNewsResponseStreamSourcesGraphSourceFromJSONTyped,
    CreateDeepNewsResponseStreamSourcesGraphSourceToJSON,
    CreateDeepNewsResponseStreamSourcesGraphSourceToJSONTyped,
} from './CreateDeepNewsResponseStreamSourcesGraphSource';
import type { CreateDeepNewsResponseStreamSourcesChartSource } from './CreateDeepNewsResponseStreamSourcesChartSource';
import {
    CreateDeepNewsResponseStreamSourcesChartSourceFromJSON,
    CreateDeepNewsResponseStreamSourcesChartSourceFromJSONTyped,
    CreateDeepNewsResponseStreamSourcesChartSourceToJSON,
    CreateDeepNewsResponseStreamSourcesChartSourceToJSONTyped,
} from './CreateDeepNewsResponseStreamSourcesChartSource';
import type { ChartResponse } from './ChartResponse';
import {
    ChartResponseFromJSON,
    ChartResponseFromJSONTyped,
    ChartResponseToJSON,
    ChartResponseToJSONTyped,
} from './ChartResponse';
import type { CreateDeepNewsResponseStreamSourcesNewsSource } from './CreateDeepNewsResponseStreamSourcesNewsSource';
import {
    CreateDeepNewsResponseStreamSourcesNewsSourceFromJSON,
    CreateDeepNewsResponseStreamSourcesNewsSourceFromJSONTyped,
    CreateDeepNewsResponseStreamSourcesNewsSourceToJSON,
    CreateDeepNewsResponseStreamSourcesNewsSourceToJSONTyped,
} from './CreateDeepNewsResponseStreamSourcesNewsSource';
import type { CreateDeepNewsResponseStreamSourcesWebSource } from './CreateDeepNewsResponseStreamSourcesWebSource';
import {
    CreateDeepNewsResponseStreamSourcesWebSourceFromJSON,
    CreateDeepNewsResponseStreamSourcesWebSourceFromJSONTyped,
    CreateDeepNewsResponseStreamSourcesWebSourceToJSON,
    CreateDeepNewsResponseStreamSourcesWebSourceToJSONTyped,
} from './CreateDeepNewsResponseStreamSourcesWebSource';

/**
 * 
 * @export
 * @interface Source
 */
export interface Source {
    /**
     * 
     * @type {string}
     * @memberof Source
     */
    kind?: SourceKindEnum;
    /**
     * 
     * @type {ChartResponse}
     * @memberof Source
     */
    data: ChartResponse;
}


/**
 * @export
 */
export const SourceKindEnum = {
    Chart: 'chart'
} as const;
export type SourceKindEnum = typeof SourceKindEnum[keyof typeof SourceKindEnum];


/**
 * Check if a given object implements the Source interface.
 */
export function instanceOfSource(value: object): value is Source {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SourceFromJSON(json: any): Source {
    return SourceFromJSONTyped(json, false);
}

export function SourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Source {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'] == null ? undefined : json['kind'],
        'data': ChartResponseFromJSON(json['data']),
    };
}

export function SourceToJSON(json: any): Source {
    return SourceToJSONTyped(json, false);
}

export function SourceToJSONTyped(value?: Source | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'data': ChartResponseToJSON(value['data']),
    };
}

