/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.22.7
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Sources1
 */
export interface Sources1 {
}

/**
 * Check if a given object implements the Sources1 interface.
 */
export function instanceOfSources1(value: object): value is Sources1 {
    return true;
}

export function Sources1FromJSON(json: any): Sources1 {
    return Sources1FromJSONTyped(json, false);
}

export function Sources1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Sources1 {
    return json;
}

export function Sources1ToJSON(json: any): Sources1 {
    return Sources1ToJSONTyped(json, false);
}

export function Sources1ToJSONTyped(value?: Sources1 | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

