/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.8.6
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Timestamp to start search from
 * @export
 * @interface StartTimestamp
 */
export interface StartTimestamp {
}

/**
 * Check if a given object implements the StartTimestamp interface.
 */
export function instanceOfStartTimestamp(value: object): boolean {
    return true;
}

export function StartTimestampFromJSON(json: any): StartTimestamp {
    return StartTimestampFromJSONTyped(json, false);
}

export function StartTimestampFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartTimestamp {
    return json;
}

export function StartTimestampToJSON(value?: StartTimestamp | null): any {
    return value;
}

