/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.9.1
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Start timestamp to filter results on.
 * @export
 * @interface StartTimestamp2
 */
export interface StartTimestamp2 {
}

/**
 * Check if a given object implements the StartTimestamp2 interface.
 */
export function instanceOfStartTimestamp2(value: object): boolean {
    return true;
}

export function StartTimestamp2FromJSON(json: any): StartTimestamp2 {
    return StartTimestamp2FromJSONTyped(json, false);
}

export function StartTimestamp2FromJSONTyped(json: any, ignoreDiscriminator: boolean): StartTimestamp2 {
    return json;
}

export function StartTimestamp2ToJSON(value?: StartTimestamp2 | null): any {
    return value;
}

