/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API
 *
 * The version of the OpenAPI document: 0.18.6
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Stop1
 */
export interface Stop1 {
}

/**
 * Check if a given object implements the Stop1 interface.
 */
export function instanceOfStop1(value: object): boolean {
    return true;
}

export function Stop1FromJSON(json: any): Stop1 {
    return Stop1FromJSONTyped(json, false);
}

export function Stop1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Stop1 {
    return json;
}

export function Stop1ToJSON(value?: Stop1 | null): any {
    return value;
}

