/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.22
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TopNDomainsByHitsItem
 */
export interface TopNDomainsByHitsItem {
    /**
     * 
     * @type {string}
     * @memberof TopNDomainsByHitsItem
     */
    domain: string;
    /**
     * 
     * @type {number}
     * @memberof TopNDomainsByHitsItem
     */
    hitCount: number;
}

/**
 * Check if a given object implements the TopNDomainsByHitsItem interface.
 */
export function instanceOfTopNDomainsByHitsItem(value: object): value is TopNDomainsByHitsItem {
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('hitCount' in value) || value['hitCount'] === undefined) return false;
    return true;
}

export function TopNDomainsByHitsItemFromJSON(json: any): TopNDomainsByHitsItem {
    return TopNDomainsByHitsItemFromJSONTyped(json, false);
}

export function TopNDomainsByHitsItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopNDomainsByHitsItem {
    if (json == null) {
        return json;
    }
    return {
        
        'domain': json['domain'],
        'hitCount': json['hit_count'],
    };
}

export function TopNDomainsByHitsItemToJSON(json: any): TopNDomainsByHitsItem {
    return TopNDomainsByHitsItemToJSONTyped(json, false);
}

export function TopNDomainsByHitsItemToJSONTyped(value?: TopNDomainsByHitsItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domain': value['domain'],
        'hit_count': value['hitCount'],
    };
}

