/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.45
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TriggersInner } from './TriggersInner';
import {
    TriggersInnerFromJSON,
    TriggersInnerFromJSONTyped,
    TriggersInnerToJSON,
    TriggersInnerToJSONTyped,
} from './TriggersInner';
import type { SourcesInner } from './SourcesInner';
import {
    SourcesInnerFromJSON,
    SourcesInnerFromJSONTyped,
    SourcesInnerToJSON,
    SourcesInnerToJSONTyped,
} from './SourcesInner';
import type { ReportRequest } from './ReportRequest';
import {
    ReportRequestFromJSON,
    ReportRequestFromJSONTyped,
    ReportRequestToJSON,
    ReportRequestToJSONTyped,
} from './ReportRequest';

/**
 * 
 * @export
 * @interface UpdateAlertRequest
 */
export interface UpdateAlertRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateAlertRequest
     */
    query?: string | null;
    /**
     * 
     * @type {Array<SourcesInner>}
     * @memberof UpdateAlertRequest
     */
    sources?: Array<SourcesInner>;
    /**
     * 
     * @type {string}
     * @memberof UpdateAlertRequest
     */
    alertType?: UpdateAlertRequestAlertTypeEnum | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAlertRequest
     */
    model?: UpdateAlertRequestModelEnum | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAlertRequest
     */
    cron?: string | null;
    /**
     * 
     * @type {Array<TriggersInner>}
     * @memberof UpdateAlertRequest
     */
    triggers?: Array<TriggersInner>;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateAlertRequest
     */
    alwaysTrigger?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateAlertRequest
     */
    repeat?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateAlertRequest
     */
    active?: boolean | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdateAlertRequest
     */
    expiresAt?: Date | null;
    /**
     * 
     * @type {ReportRequest}
     * @memberof UpdateAlertRequest
     */
    report?: ReportRequest | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAlertRequest
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAlertRequest
     */
    shareLink?: string | null;
}


/**
 * @export
 */
export const UpdateAlertRequestAlertTypeEnum = {
    AlwaysAlertWhen: 'AlwaysAlertWhen',
    AlertOnceIf: 'AlertOnceIf',
    ReportAbout: 'ReportAbout'
} as const;
export type UpdateAlertRequestAlertTypeEnum = typeof UpdateAlertRequestAlertTypeEnum[keyof typeof UpdateAlertRequestAlertTypeEnum];

/**
 * @export
 */
export const UpdateAlertRequestModelEnum = {
    MetaLlamaMetaLlama318BInstruct: 'meta-llama/Meta-Llama-3.1-8B-Instruct',
    Gpt4oMini: 'gpt-4o-mini',
    Gpt5Mini: 'gpt-5-mini',
    Gpt5Nano: 'gpt-5-nano',
    Gpt4o: 'gpt-4o',
    O3Mini: 'o3-mini',
    MetaLlamaMetaLlama3370BInstruct: 'meta-llama/Meta-Llama-3.3-70B-Instruct',
    Gpt4120250414: 'gpt-4.1-2025-04-14',
    Gpt41Nano20250414: 'gpt-4.1-nano-2025-04-14',
    Gpt41Mini20250414: 'gpt-4.1-mini-2025-04-14'
} as const;
export type UpdateAlertRequestModelEnum = typeof UpdateAlertRequestModelEnum[keyof typeof UpdateAlertRequestModelEnum];


/**
 * Check if a given object implements the UpdateAlertRequest interface.
 */
export function instanceOfUpdateAlertRequest(value: object): value is UpdateAlertRequest {
    return true;
}

export function UpdateAlertRequestFromJSON(json: any): UpdateAlertRequest {
    return UpdateAlertRequestFromJSONTyped(json, false);
}

export function UpdateAlertRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAlertRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'] == null ? undefined : json['query'],
        'sources': json['sources'] == null ? undefined : ((json['sources'] as Array<any>).map(SourcesInnerFromJSON)),
        'alertType': json['alert_type'] == null ? undefined : json['alert_type'],
        'model': json['model'] == null ? undefined : json['model'],
        'cron': json['cron'] == null ? undefined : json['cron'],
        'triggers': json['triggers'] == null ? undefined : ((json['triggers'] as Array<any>).map(TriggersInnerFromJSON)),
        'alwaysTrigger': json['always_trigger'] == null ? undefined : json['always_trigger'],
        'repeat': json['repeat'] == null ? undefined : json['repeat'],
        'active': json['active'] == null ? undefined : json['active'],
        'expiresAt': json['expires_at'] == null ? undefined : (new Date(json['expires_at'])),
        'report': json['report'] == null ? undefined : ReportRequestFromJSON(json['report']),
        'title': json['title'] == null ? undefined : json['title'],
        'shareLink': json['share_link'] == null ? undefined : json['share_link'],
    };
}

export function UpdateAlertRequestToJSON(json: any): UpdateAlertRequest {
    return UpdateAlertRequestToJSONTyped(json, false);
}

export function UpdateAlertRequestToJSONTyped(value?: UpdateAlertRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'query': value['query'],
        'sources': value['sources'] == null ? undefined : ((value['sources'] as Array<any>).map(SourcesInnerToJSON)),
        'alert_type': value['alertType'],
        'model': value['model'],
        'cron': value['cron'],
        'triggers': value['triggers'] == null ? undefined : ((value['triggers'] as Array<any>).map(TriggersInnerToJSON)),
        'always_trigger': value['alwaysTrigger'],
        'repeat': value['repeat'],
        'active': value['active'],
        'expires_at': value['expiresAt'] == null ? undefined : ((value['expiresAt'] as any).toISOString()),
        'report': ReportRequestToJSON(value['report']),
        'title': value['title'],
        'share_link': value['shareLink'],
    };
}

