/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.28
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScrapedURLItem } from './ScrapedURLItem';
import {
    ScrapedURLItemFromJSON,
    ScrapedURLItemFromJSONTyped,
    ScrapedURLItemToJSON,
    ScrapedURLItemToJSONTyped,
} from './ScrapedURLItem';

/**
 * 
 * @export
 * @interface URLIndexingRequest
 */
export interface URLIndexingRequest {
    /**
     * 
     * @type {Date}
     * @memberof URLIndexingRequest
     */
    startTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof URLIndexingRequest
     */
    endTime: Date;
    /**
     * 
     * @type {Array<ScrapedURLItem>}
     * @memberof URLIndexingRequest
     */
    urls: Array<ScrapedURLItem>;
}

/**
 * Check if a given object implements the URLIndexingRequest interface.
 */
export function instanceOfURLIndexingRequest(value: object): value is URLIndexingRequest {
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('endTime' in value) || value['endTime'] === undefined) return false;
    if (!('urls' in value) || value['urls'] === undefined) return false;
    return true;
}

export function URLIndexingRequestFromJSON(json: any): URLIndexingRequest {
    return URLIndexingRequestFromJSONTyped(json, false);
}

export function URLIndexingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): URLIndexingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'startTime': (new Date(json['start_time'])),
        'endTime': (new Date(json['end_time'])),
        'urls': ((json['urls'] as Array<any>).map(ScrapedURLItemFromJSON)),
    };
}

export function URLIndexingRequestToJSON(json: any): URLIndexingRequest {
    return URLIndexingRequestToJSONTyped(json, false);
}

export function URLIndexingRequestToJSONTyped(value?: URLIndexingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start_time': ((value['startTime']).toISOString()),
        'end_time': ((value['endTime']).toISOString()),
        'urls': ((value['urls'] as Array<any>).map(ScrapedURLItemToJSON)),
    };
}

