/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.43
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A unique identifier for the end-user, useful for tracking and abuse detection.
 * @export
 * @interface User1
 */
export interface User1 {
}

/**
 * Check if a given object implements the User1 interface.
 */
export function instanceOfUser1(value: object): value is User1 {
    return true;
}

export function User1FromJSON(json: any): User1 {
    return User1FromJSONTyped(json, false);
}

export function User1FromJSONTyped(json: any, ignoreDiscriminator: boolean): User1 {
    return json;
}

export function User1ToJSON(json: any): User1 {
    return User1ToJSONTyped(json, false);
}

export function User1ToJSONTyped(value?: User1 | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

