/* tslint:disable */
/* eslint-disable */
/**
 * AskNews API
 * AskNews API [![status](https://status.asknews.app/api/badge/2/status?style=for-the-badge)](https://status.asknews.app/status/prod)
 *
 * The version of the OpenAPI document: 0.24.54
 * Contact: contact@emergentmethods.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebSearchResult } from './WebSearchResult';
import {
    WebSearchResultFromJSON,
    WebSearchResultFromJSONTyped,
    WebSearchResultToJSON,
    WebSearchResultToJSONTyped,
} from './WebSearchResult';
import type { Offset4 } from './Offset4';
import {
    Offset4FromJSON,
    Offset4FromJSONTyped,
    Offset4ToJSON,
    Offset4ToJSONTyped,
} from './Offset4';

/**
 * 
 * @export
 * @interface WebSearchResponse
 */
export interface WebSearchResponse {
    /**
     * 
     * @type {string}
     * @memberof WebSearchResponse
     */
    asString: string;
    /**
     * 
     * @type {Array<WebSearchResult>}
     * @memberof WebSearchResponse
     */
    asDicts: Array<WebSearchResult>;
    /**
     * 
     * @type {Offset4}
     * @memberof WebSearchResponse
     */
    offset?: Offset4 | null;
}

/**
 * Check if a given object implements the WebSearchResponse interface.
 */
export function instanceOfWebSearchResponse(value: object): value is WebSearchResponse {
    if (!('asString' in value) || value['asString'] === undefined) return false;
    if (!('asDicts' in value) || value['asDicts'] === undefined) return false;
    return true;
}

export function WebSearchResponseFromJSON(json: any): WebSearchResponse {
    return WebSearchResponseFromJSONTyped(json, false);
}

export function WebSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebSearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'asString': json['as_string'],
        'asDicts': ((json['as_dicts'] as Array<any>).map(WebSearchResultFromJSON)),
        'offset': json['offset'] == null ? undefined : Offset4FromJSON(json['offset']),
    };
}

export function WebSearchResponseToJSON(json: any): WebSearchResponse {
    return WebSearchResponseToJSONTyped(json, false);
}

export function WebSearchResponseToJSONTyped(value?: WebSearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'as_string': value['asString'],
        'as_dicts': ((value['asDicts'] as Array<any>).map(WebSearchResultToJSON)),
        'offset': Offset4ToJSON(value['offset']),
    };
}

